"""
Regime Strategy SL/TP Parameters - TIERED QUALITY SYSTEM
========================================================
Auto-generated by regime_sltp_gen_updated_v2.py
Contains optimized SL/TP for RegimeAdaptive strategy.

QUALITY TIERS:
  Tier 1: WR ≥ 40%, PF ≥ 1.3 (High confidence)
  Tier 2: WR ≥ 35%, PF ≥ 1.1 (Medium confidence)
  Tier 3: Positive PnL only  (Low confidence - reduce position size)
  Tier 4: Default params     (No reliable data - consider skipping)

Each combo was tested in BOTH normal and reversed directions.
Only marked as reverted if reversed direction had better score.

Usage:
    from regime_sltp_params import get_regime_sltp, is_reverted_combo, get_quality_tier
    
    sltp = get_regime_sltp('LONG', 'Q1', 'W1', 'MON', 'NY_AM')
    reverted = is_reverted_combo('Q1', 'W1', 'MON', 'NY_AM')
    tier = get_quality_tier('Q1', 'W1', 'MON', 'NY_AM')
"""

# ============================================================
# REVERTED COMBOS - Reversed direction performed better
# Total: 150 combos
# ============================================================
REVERTED_COMBOS = {
    'Q1_W1_MON_ASIA',  # WR: 41.1%, Tier 2 ⚠
    'Q1_W1_MON_NY_AM',  # WR: 51.6%, Tier 2 ⚠
    'Q1_W1_MON_NY_PM',  # WR: 54.1%, Tier 1 ✓
    'Q1_W1_THU_ASIA',  # WR: 42.3%, Tier 2 ⚠
    'Q1_W1_THU_NY_AM',  # WR: 42.7%, Tier 2 ⚠
    'Q1_W1_THU_NY_PM',  # WR: 35.6%, Tier 2 ⚠
    'Q1_W1_TUE_LONDON',  # WR: 35.6%, Tier 2 ⚠
    'Q1_W1_TUE_NY_PM',  # WR: 39.8%, Tier 2 ⚠
    'Q1_W1_WED_NY_PM',  # WR: 47.8%, Tier 2 ⚠
    'Q1_W2_FRI_ASIA',  # WR: 43.8%, Tier 2 ⚠
    'Q1_W2_FRI_LONDON',  # WR: 48.0%, Tier 2 ⚠
    'Q1_W2_FRI_NY_AM',  # WR: 50.7%, Tier 2 ⚠
    'Q1_W2_MON_ASIA',  # WR: 37.3%, Tier 2 ⚠
    'Q1_W2_MON_NY_AM',  # WR: 41.9%, Tier 2 ⚠
    'Q1_W2_THU_NY_AM',  # WR: 43.8%, Tier 2 ⚠
    'Q1_W2_TUE_ASIA',  # WR: 36.9%, Tier 2 ⚠
    'Q1_W2_TUE_NY_AM',  # WR: 40.9%, Tier 2 ⚠
    'Q1_W2_WED_ASIA',  # WR: 45.6%, Tier 2 ⚠
    'Q1_W2_WED_LONDON',  # WR: 48.0%, Tier 2 ⚠
    'Q1_W3_FRI_LONDON',  # WR: 49.4%, Tier 2 ⚠
    'Q1_W3_FRI_NY_AM',  # WR: 38.2%, Tier 2 ⚠
    'Q1_W3_MON_ASIA',  # WR: 43.8%, Tier 2 ⚠
    'Q1_W3_MON_NY_AM',  # WR: 50.6%, Tier 1 ✓
    'Q1_W3_THU_ASIA',  # WR: 44.3%, Tier 2 ⚠
    'Q1_W3_THU_LONDON',  # WR: 43.9%, Tier 1 ✓
    'Q1_W3_THU_NY_AM',  # WR: 47.8%, Tier 3 ⚠⚠
    'Q1_W3_THU_NY_PM',  # WR: 49.7%, Tier 2 ⚠
    'Q1_W3_WED_NY_AM',  # WR: 49.5%, Tier 2 ⚠
    'Q1_W3_WED_NY_PM',  # WR: 45.3%, Tier 2 ⚠
    'Q1_W4_FRI_ASIA',  # WR: 38.8%, Tier 2 ⚠
    'Q1_W4_FRI_LONDON',  # WR: 49.1%, Tier 2 ⚠
    'Q1_W4_FRI_NY_AM',  # WR: 31.5%, Tier 3 ⚠⚠
    'Q1_W4_MON_ASIA',  # WR: 36.4%, Tier 2 ⚠
    'Q1_W4_MON_NY_AM',  # WR: 50.7%, Tier 2 ⚠
    'Q1_W4_MON_NY_PM',  # WR: 49.1%, Tier 2 ⚠
    'Q1_W4_THU_ASIA',  # WR: 45.5%, Tier 2 ⚠
    'Q1_W4_THU_LONDON',  # WR: 47.0%, Tier 3 ⚠⚠
    'Q1_W4_THU_NY_PM',  # WR: 46.4%, Tier 3 ⚠⚠
    'Q1_W4_TUE_NY_PM',  # WR: 43.0%, Tier 3 ⚠⚠
    'Q1_W4_WED_LONDON',  # WR: 46.6%, Tier 2 ⚠
    'Q1_W4_WED_NY_AM',  # WR: 47.2%, Tier 2 ⚠
    'Q1_W4_WED_NY_PM',  # WR: 49.2%, Tier 2 ⚠
    'Q2_W1_MON_ASIA',  # WR: 34.1%, Tier 3 ⚠⚠
    'Q2_W1_MON_NY_AM',  # WR: 38.8%, Tier 3 ⚠⚠
    'Q2_W1_THU_ASIA',  # WR: 47.2%, Tier 3 ⚠⚠
    'Q2_W1_THU_NY_PM',  # WR: 34.4%, Tier 3 ⚠⚠
    'Q2_W1_TUE_ASIA',  # WR: 47.8%, Tier 3 ⚠⚠
    'Q2_W1_TUE_LONDON',  # WR: 46.6%, Tier 2 ⚠
    'Q2_W1_TUE_NY_PM',  # WR: 46.1%, Tier 3 ⚠⚠
    'Q2_W1_WED_ASIA',  # WR: 43.9%, Tier 2 ⚠
    'Q2_W1_WED_NY_AM',  # WR: 50.9%, Tier 2 ⚠
    'Q2_W1_WED_NY_PM',  # WR: 47.8%, Tier 3 ⚠⚠
    'Q2_W2_MON_ASIA',  # WR: 48.4%, Tier 3 ⚠⚠
    'Q2_W2_MON_NY_AM',  # WR: 48.6%, Tier 2 ⚠
    'Q2_W2_THU_NY_AM',  # WR: 42.6%, Tier 3 ⚠⚠
    'Q2_W2_WED_NY_AM',  # WR: 45.0%, Tier 1 ✓
    'Q2_W2_WED_NY_PM',  # WR: 49.6%, Tier 2 ⚠
    'Q2_W3_FRI_LONDON',  # WR: 46.0%, Tier 2 ⚠
    'Q2_W3_FRI_NY_AM',  # WR: 48.5%, Tier 2 ⚠
    'Q2_W3_FRI_NY_PM',  # WR: 52.1%, Tier 1 ✓
    'Q2_W3_MON_NY_AM',  # WR: 53.0%, Tier 1 ✓
    'Q2_W3_THU_ASIA',  # WR: 53.9%, Tier 1 ✓
    'Q2_W3_THU_NY_PM',  # WR: 50.0%, Tier 2 ⚠
    'Q2_W3_TUE_LONDON',  # WR: 40.4%, Tier 2 ⚠
    'Q2_W3_TUE_NY_AM',  # WR: 50.3%, Tier 2 ⚠
    'Q2_W3_TUE_NY_PM',  # WR: 46.7%, Tier 3 ⚠⚠
    'Q2_W4_FRI_ASIA',  # WR: 44.4%, Tier 1 ✓
    'Q2_W4_FRI_NY_AM',  # WR: 46.6%, Tier 2 ⚠
    'Q2_W4_MON_ASIA',  # WR: 35.7%, Tier 2 ⚠
    'Q2_W4_MON_LONDON',  # WR: 50.3%, Tier 2 ⚠
    'Q2_W4_MON_NY_AM',  # WR: 50.8%, Tier 2 ⚠
    'Q2_W4_MON_NY_PM',  # WR: 47.0%, Tier 2 ⚠
    'Q2_W4_THU_ASIA',  # WR: 41.2%, Tier 2 ⚠
    'Q2_W4_THU_LONDON',  # WR: 47.5%, Tier 2 ⚠
    'Q2_W4_THU_NY_AM',  # WR: 50.1%, Tier 2 ⚠
    'Q2_W4_THU_NY_PM',  # WR: 39.6%, Tier 2 ⚠
    'Q2_W4_TUE_LONDON',  # WR: 51.0%, Tier 2 ⚠
    'Q2_W4_WED_NY_AM',  # WR: 45.6%, Tier 2 ⚠
    'Q2_W4_WED_NY_PM',  # WR: 35.6%, Tier 2 ⚠
    'Q3_W1_FRI_LONDON',  # WR: 46.5%, Tier 3 ⚠⚠
    'Q3_W1_FRI_NY_PM',  # WR: 39.9%, Tier 2 ⚠
    'Q3_W1_MON_NY_PM',  # WR: 45.7%, Tier 3 ⚠⚠
    'Q3_W1_THU_LONDON',  # WR: 40.0%, Tier 2 ⚠
    'Q3_W1_THU_NY_AM',  # WR: 36.0%, Tier 2 ⚠
    'Q3_W1_TUE_ASIA',  # WR: 41.1%, Tier 2 ⚠
    'Q3_W1_TUE_LONDON',  # WR: 52.9%, Tier 1 ✓
    'Q3_W1_TUE_NY_AM',  # WR: 49.5%, Tier 2 ⚠
    'Q3_W1_WED_ASIA',  # WR: 44.1%, Tier 2 ⚠
    'Q3_W2_FRI_ASIA',  # WR: 36.6%, Tier 2 ⚠
    'Q3_W2_FRI_NY_AM',  # WR: 48.6%, Tier 3 ⚠⚠
    'Q3_W2_FRI_NY_PM',  # WR: 45.9%, Tier 2 ⚠
    'Q3_W2_MON_LONDON',  # WR: 41.3%, Tier 2 ⚠
    'Q3_W2_MON_NY_AM',  # WR: 45.0%, Tier 2 ⚠
    'Q3_W2_THU_ASIA',  # WR: 41.2%, Tier 2 ⚠
    'Q3_W2_THU_LONDON',  # WR: 50.9%, Tier 2 ⚠
    'Q3_W2_THU_NY_AM',  # WR: 47.1%, Tier 2 ⚠
    'Q3_W2_TUE_LONDON',  # WR: 48.5%, Tier 2 ⚠
    'Q3_W2_WED_NY_AM',  # WR: 36.7%, Tier 2 ⚠
    'Q3_W2_WED_NY_PM',  # WR: 42.6%, Tier 2 ⚠
    'Q3_W3_FRI_NY_AM',  # WR: 48.9%, Tier 2 ⚠
    'Q3_W3_THU_ASIA',  # WR: 43.9%, Tier 2 ⚠
    'Q3_W3_THU_LONDON',  # WR: 46.9%, Tier 1 ✓
    'Q3_W3_TUE_NY_AM',  # WR: 45.9%, Tier 2 ⚠
    'Q3_W3_TUE_NY_PM',  # WR: 46.6%, Tier 3 ⚠⚠
    'Q3_W4_FRI_ASIA',  # WR: 46.1%, Tier 2 ⚠
    'Q3_W4_FRI_LONDON',  # WR: 49.8%, Tier 2 ⚠
    'Q3_W4_FRI_NY_AM',  # WR: 45.2%, Tier 3 ⚠⚠
    'Q3_W4_FRI_NY_PM',  # WR: 48.7%, Tier 2 ⚠
    'Q3_W4_MON_ASIA',  # WR: 40.9%, Tier 2 ⚠
    'Q3_W4_MON_NY_PM',  # WR: 45.3%, Tier 2 ⚠
    'Q3_W4_THU_ASIA',  # WR: 40.1%, Tier 2 ⚠
    'Q3_W4_TUE_ASIA',  # WR: 43.7%, Tier 3 ⚠⚠
    'Q3_W4_TUE_LONDON',  # WR: 52.3%, Tier 1 ✓
    'Q3_W4_WED_LONDON',  # WR: 46.2%, Tier 2 ⚠
    'Q4_W1_FRI_NY_PM',  # WR: 51.3%, Tier 1 ✓
    'Q4_W1_MON_ASIA',  # WR: 40.0%, Tier 2 ⚠
    'Q4_W1_MON_NY_AM',  # WR: 48.0%, Tier 2 ⚠
    'Q4_W1_MON_NY_PM',  # WR: 47.0%, Tier 3 ⚠⚠
    'Q4_W1_THU_NY_AM',  # WR: 40.3%, Tier 2 ⚠
    'Q4_W1_TUE_NY_AM',  # WR: 55.4%, Tier 1 ✓
    'Q4_W1_TUE_NY_PM',  # WR: 48.8%, Tier 2 ⚠
    'Q4_W1_WED_LONDON',  # WR: 39.5%, Tier 3 ⚠⚠
    'Q4_W1_WED_NY_AM',  # WR: 45.7%, Tier 2 ⚠
    'Q4_W1_WED_NY_PM',  # WR: 46.9%, Tier 2 ⚠
    'Q4_W2_FRI_NY_PM',  # WR: 46.3%, Tier 2 ⚠
    'Q4_W2_MON_ASIA',  # WR: 48.4%, Tier 3 ⚠⚠
    'Q4_W2_MON_LONDON',  # WR: 41.6%, Tier 2 ⚠
    'Q4_W2_MON_NY_PM',  # WR: 49.2%, Tier 2 ⚠
    'Q4_W2_THU_LONDON',  # WR: 49.0%, Tier 2 ⚠
    'Q4_W2_TUE_LONDON',  # WR: 45.2%, Tier 2 ⚠
    'Q4_W2_TUE_NY_AM',  # WR: 44.6%, Tier 1 ✓
    'Q4_W2_WED_NY_PM',  # WR: 54.6%, Tier 1 ✓
    'Q4_W3_FRI_ASIA',  # WR: 40.0%, Tier 2 ⚠
    'Q4_W3_FRI_LONDON',  # WR: 49.0%, Tier 2 ⚠
    'Q4_W3_MON_LONDON',  # WR: 43.5%, Tier 2 ⚠
    'Q4_W3_MON_NY_AM',  # WR: 40.8%, Tier 2 ⚠
    'Q4_W3_TUE_LONDON',  # WR: 45.7%, Tier 2 ⚠
    'Q4_W3_TUE_NY_AM',  # WR: 52.6%, Tier 1 ✓
    'Q4_W3_WED_NY_AM',  # WR: 57.4%, Tier 1 ✓
    'Q4_W4_FRI_ASIA',  # WR: 39.6%, Tier 2 ⚠
    'Q4_W4_FRI_LONDON',  # WR: 47.0%, Tier 2 ⚠
    'Q4_W4_FRI_NY_AM',  # WR: 40.6%, Tier 2 ⚠
    'Q4_W4_FRI_NY_PM',  # WR: 38.8%, Tier 2 ⚠
    'Q4_W4_MON_LONDON',  # WR: 50.1%, Tier 1 ✓
    'Q4_W4_MON_NY_PM',  # WR: 46.5%, Tier 2 ⚠
    'Q4_W4_THU_LONDON',  # WR: 50.9%, Tier 2 ⚠
    'Q4_W4_THU_NY_PM',  # WR: 52.6%, Tier 1 ✓
    'Q4_W4_TUE_ASIA',  # WR: 35.8%, Tier 2 ⚠
    'Q4_W4_TUE_LONDON',  # WR: 45.8%, Tier 3 ⚠⚠
    'Q4_W4_WED_ASIA',  # WR: 42.1%, Tier 3 ⚠⚠
}

# ============================================================
# QUALITY TIERS - Reliability rating for each combo
# ============================================================
QUALITY_TIERS = {
    'Q1_W1_FRI_ASIA': 2,
    'Q1_W1_FRI_LONDON': 2,
    'Q1_W1_FRI_NY_AM': 2,
    'Q1_W1_FRI_NY_PM': 2,
    'Q1_W1_MON_ASIA': 2,
    'Q1_W1_MON_LONDON': 2,
    'Q1_W1_MON_NY_AM': 2,
    'Q1_W1_MON_NY_PM': 1,
    'Q1_W1_THU_ASIA': 2,
    'Q1_W1_THU_LONDON': 2,
    'Q1_W1_THU_NY_AM': 2,
    'Q1_W1_THU_NY_PM': 2,
    'Q1_W1_TUE_ASIA': 2,
    'Q1_W1_TUE_LONDON': 2,
    'Q1_W1_TUE_NY_AM': 2,
    'Q1_W1_TUE_NY_PM': 2,
    'Q1_W1_WED_ASIA': 2,
    'Q1_W1_WED_LONDON': 2,
    'Q1_W1_WED_NY_AM': 2,
    'Q1_W1_WED_NY_PM': 2,
    'Q1_W2_FRI_ASIA': 2,
    'Q1_W2_FRI_LONDON': 2,
    'Q1_W2_FRI_NY_AM': 2,
    'Q1_W2_FRI_NY_PM': 2,
    'Q1_W2_MON_ASIA': 2,
    'Q1_W2_MON_LONDON': 1,
    'Q1_W2_MON_NY_AM': 2,
    'Q1_W2_MON_NY_PM': 2,
    'Q1_W2_THU_ASIA': 2,
    'Q1_W2_THU_LONDON': 2,
    'Q1_W2_THU_NY_AM': 2,
    'Q1_W2_THU_NY_PM': 2,
    'Q1_W2_TUE_ASIA': 2,
    'Q1_W2_TUE_LONDON': 2,
    'Q1_W2_TUE_NY_AM': 2,
    'Q1_W2_TUE_NY_PM': 2,
    'Q1_W2_WED_ASIA': 2,
    'Q1_W2_WED_LONDON': 2,
    'Q1_W2_WED_NY_AM': 2,
    'Q1_W2_WED_NY_PM': 2,
    'Q1_W3_FRI_ASIA': 2,
    'Q1_W3_FRI_LONDON': 2,
    'Q1_W3_FRI_NY_AM': 2,
    'Q1_W3_FRI_NY_PM': 2,
    'Q1_W3_MON_ASIA': 2,
    'Q1_W3_MON_LONDON': 2,
    'Q1_W3_MON_NY_AM': 1,
    'Q1_W3_MON_NY_PM': 1,
    'Q1_W3_THU_ASIA': 2,
    'Q1_W3_THU_LONDON': 1,
    'Q1_W3_THU_NY_AM': 3,
    'Q1_W3_THU_NY_PM': 2,
    'Q1_W3_TUE_ASIA': 2,
    'Q1_W3_TUE_LONDON': 2,
    'Q1_W3_TUE_NY_AM': 2,
    'Q1_W3_TUE_NY_PM': 2,
    'Q1_W3_WED_ASIA': 1,
    'Q1_W3_WED_LONDON': 3,
    'Q1_W3_WED_NY_AM': 2,
    'Q1_W3_WED_NY_PM': 2,
    'Q1_W4_FRI_ASIA': 2,
    'Q1_W4_FRI_LONDON': 2,
    'Q1_W4_FRI_NY_AM': 3,
    'Q1_W4_FRI_NY_PM': 3,
    'Q1_W4_MON_ASIA': 2,
    'Q1_W4_MON_LONDON': 2,
    'Q1_W4_MON_NY_AM': 2,
    'Q1_W4_MON_NY_PM': 2,
    'Q1_W4_THU_ASIA': 2,
    'Q1_W4_THU_LONDON': 3,
    'Q1_W4_THU_NY_AM': 2,
    'Q1_W4_THU_NY_PM': 3,
    'Q1_W4_TUE_ASIA': 3,
    'Q1_W4_TUE_LONDON': 2,
    'Q1_W4_TUE_NY_AM': 3,
    'Q1_W4_TUE_NY_PM': 3,
    'Q1_W4_WED_ASIA': 2,
    'Q1_W4_WED_LONDON': 2,
    'Q1_W4_WED_NY_AM': 2,
    'Q1_W4_WED_NY_PM': 2,
    'Q2_W1_FRI_ASIA': 1,
    'Q2_W1_FRI_LONDON': 3,
    'Q2_W1_FRI_NY_AM': 2,
    'Q2_W1_FRI_NY_PM': 2,
    'Q2_W1_MON_ASIA': 3,
    'Q2_W1_MON_LONDON': 2,
    'Q2_W1_MON_NY_AM': 3,
    'Q2_W1_MON_NY_PM': 3,
    'Q2_W1_THU_ASIA': 3,
    'Q2_W1_THU_LONDON': 3,
    'Q2_W1_THU_NY_AM': 2,
    'Q2_W1_THU_NY_PM': 3,
    'Q2_W1_TUE_ASIA': 3,
    'Q2_W1_TUE_LONDON': 2,
    'Q2_W1_TUE_NY_AM': 2,
    'Q2_W1_TUE_NY_PM': 3,
    'Q2_W1_WED_ASIA': 2,
    'Q2_W1_WED_LONDON': 2,
    'Q2_W1_WED_NY_AM': 2,
    'Q2_W1_WED_NY_PM': 3,
    'Q2_W2_FRI_ASIA': 2,
    'Q2_W2_FRI_LONDON': 2,
    'Q2_W2_FRI_NY_AM': 3,
    'Q2_W2_FRI_NY_PM': 2,
    'Q2_W2_MON_ASIA': 3,
    'Q2_W2_MON_LONDON': 1,
    'Q2_W2_MON_NY_AM': 2,
    'Q2_W2_MON_NY_PM': 2,
    'Q2_W2_THU_ASIA': 2,
    'Q2_W2_THU_LONDON': 2,
    'Q2_W2_THU_NY_AM': 3,
    'Q2_W2_THU_NY_PM': 2,
    'Q2_W2_TUE_ASIA': 3,
    'Q2_W2_TUE_LONDON': 2,
    'Q2_W2_TUE_NY_AM': 3,
    'Q2_W2_TUE_NY_PM': 2,
    'Q2_W2_WED_ASIA': 2,
    'Q2_W2_WED_LONDON': 3,
    'Q2_W2_WED_NY_AM': 1,
    'Q2_W2_WED_NY_PM': 2,
    'Q2_W3_FRI_ASIA': 2,
    'Q2_W3_FRI_LONDON': 2,
    'Q2_W3_FRI_NY_AM': 2,
    'Q2_W3_FRI_NY_PM': 1,
    'Q2_W3_MON_ASIA': 2,
    'Q2_W3_MON_LONDON': 1,
    'Q2_W3_MON_NY_AM': 1,
    'Q2_W3_MON_NY_PM': 2,
    'Q2_W3_THU_ASIA': 1,
    'Q2_W3_THU_LONDON': 2,
    'Q2_W3_THU_NY_AM': 2,
    'Q2_W3_THU_NY_PM': 2,
    'Q2_W3_TUE_ASIA': 2,
    'Q2_W3_TUE_LONDON': 2,
    'Q2_W3_TUE_NY_AM': 2,
    'Q2_W3_TUE_NY_PM': 3,
    'Q2_W3_WED_ASIA': 2,
    'Q2_W3_WED_LONDON': 2,
    'Q2_W3_WED_NY_AM': 1,
    'Q2_W3_WED_NY_PM': 1,
    'Q2_W4_FRI_ASIA': 1,
    'Q2_W4_FRI_LONDON': 3,
    'Q2_W4_FRI_NY_AM': 2,
    'Q2_W4_FRI_NY_PM': 2,
    'Q2_W4_MON_ASIA': 2,
    'Q2_W4_MON_LONDON': 2,
    'Q2_W4_MON_NY_AM': 2,
    'Q2_W4_MON_NY_PM': 2,
    'Q2_W4_THU_ASIA': 2,
    'Q2_W4_THU_LONDON': 2,
    'Q2_W4_THU_NY_AM': 2,
    'Q2_W4_THU_NY_PM': 2,
    'Q2_W4_TUE_ASIA': 3,
    'Q2_W4_TUE_LONDON': 2,
    'Q2_W4_TUE_NY_AM': 2,
    'Q2_W4_TUE_NY_PM': 2,
    'Q2_W4_WED_ASIA': 2,
    'Q2_W4_WED_LONDON': 2,
    'Q2_W4_WED_NY_AM': 2,
    'Q2_W4_WED_NY_PM': 2,
    'Q3_W1_FRI_ASIA': 1,
    'Q3_W1_FRI_LONDON': 3,
    'Q3_W1_FRI_NY_AM': 2,
    'Q3_W1_FRI_NY_PM': 2,
    'Q3_W1_MON_ASIA': 3,
    'Q3_W1_MON_LONDON': 2,
    'Q3_W1_MON_NY_AM': 2,
    'Q3_W1_MON_NY_PM': 3,
    'Q3_W1_THU_ASIA': 2,
    'Q3_W1_THU_LONDON': 2,
    'Q3_W1_THU_NY_AM': 2,
    'Q3_W1_THU_NY_PM': 2,
    'Q3_W1_TUE_ASIA': 2,
    'Q3_W1_TUE_LONDON': 1,
    'Q3_W1_TUE_NY_AM': 2,
    'Q3_W1_TUE_NY_PM': 2,
    'Q3_W1_WED_ASIA': 2,
    'Q3_W1_WED_LONDON': 2,
    'Q3_W1_WED_NY_AM': 2,
    'Q3_W1_WED_NY_PM': 2,
    'Q3_W2_FRI_ASIA': 2,
    'Q3_W2_FRI_LONDON': 2,
    'Q3_W2_FRI_NY_AM': 3,
    'Q3_W2_FRI_NY_PM': 2,
    'Q3_W2_MON_ASIA': 2,
    'Q3_W2_MON_LONDON': 2,
    'Q3_W2_MON_NY_AM': 2,
    'Q3_W2_MON_NY_PM': 2,
    'Q3_W2_THU_ASIA': 2,
    'Q3_W2_THU_LONDON': 2,
    'Q3_W2_THU_NY_AM': 2,
    'Q3_W2_THU_NY_PM': 1,
    'Q3_W2_TUE_ASIA': 2,
    'Q3_W2_TUE_LONDON': 2,
    'Q3_W2_TUE_NY_AM': 1,
    'Q3_W2_TUE_NY_PM': 2,
    'Q3_W2_WED_ASIA': 3,
    'Q3_W2_WED_LONDON': 2,
    'Q3_W2_WED_NY_AM': 2,
    'Q3_W2_WED_NY_PM': 2,
    'Q3_W3_FRI_ASIA': 2,
    'Q3_W3_FRI_LONDON': 3,
    'Q3_W3_FRI_NY_AM': 2,
    'Q3_W3_FRI_NY_PM': 2,
    'Q3_W3_MON_ASIA': 2,
    'Q3_W3_MON_LONDON': 1,
    'Q3_W3_MON_NY_AM': 2,
    'Q3_W3_MON_NY_PM': 2,
    'Q3_W3_THU_ASIA': 2,
    'Q3_W3_THU_LONDON': 1,
    'Q3_W3_THU_NY_AM': 2,
    'Q3_W3_THU_NY_PM': 3,
    'Q3_W3_TUE_ASIA': 2,
    'Q3_W3_TUE_LONDON': 2,
    'Q3_W3_TUE_NY_AM': 2,
    'Q3_W3_TUE_NY_PM': 3,
    'Q3_W3_WED_ASIA': 1,
    'Q3_W3_WED_LONDON': 2,
    'Q3_W3_WED_NY_AM': 2,
    'Q3_W3_WED_NY_PM': 2,
    'Q3_W4_FRI_ASIA': 2,
    'Q3_W4_FRI_LONDON': 2,
    'Q3_W4_FRI_NY_AM': 3,
    'Q3_W4_FRI_NY_PM': 2,
    'Q3_W4_MON_ASIA': 2,
    'Q3_W4_MON_LONDON': 2,
    'Q3_W4_MON_NY_AM': 3,
    'Q3_W4_MON_NY_PM': 2,
    'Q3_W4_THU_ASIA': 2,
    'Q3_W4_THU_LONDON': 3,
    'Q3_W4_THU_NY_AM': 2,
    'Q3_W4_THU_NY_PM': 2,
    'Q3_W4_TUE_ASIA': 3,
    'Q3_W4_TUE_LONDON': 1,
    'Q3_W4_TUE_NY_AM': 2,
    'Q3_W4_TUE_NY_PM': 2,
    'Q3_W4_WED_ASIA': 2,
    'Q3_W4_WED_LONDON': 2,
    'Q3_W4_WED_NY_AM': 2,
    'Q3_W4_WED_NY_PM': 3,
    'Q4_W1_FRI_ASIA': 2,
    'Q4_W1_FRI_LONDON': 2,
    'Q4_W1_FRI_NY_AM': 2,
    'Q4_W1_FRI_NY_PM': 1,
    'Q4_W1_MON_ASIA': 2,
    'Q4_W1_MON_LONDON': 2,
    'Q4_W1_MON_NY_AM': 2,
    'Q4_W1_MON_NY_PM': 3,
    'Q4_W1_THU_ASIA': 2,
    'Q4_W1_THU_LONDON': 3,
    'Q4_W1_THU_NY_AM': 2,
    'Q4_W1_THU_NY_PM': 2,
    'Q4_W1_TUE_ASIA': 2,
    'Q4_W1_TUE_LONDON': 2,
    'Q4_W1_TUE_NY_AM': 1,
    'Q4_W1_TUE_NY_PM': 2,
    'Q4_W1_WED_ASIA': 2,
    'Q4_W1_WED_LONDON': 3,
    'Q4_W1_WED_NY_AM': 2,
    'Q4_W1_WED_NY_PM': 2,
    'Q4_W2_FRI_ASIA': 1,
    'Q4_W2_FRI_LONDON': 2,
    'Q4_W2_FRI_NY_AM': 2,
    'Q4_W2_FRI_NY_PM': 2,
    'Q4_W2_MON_ASIA': 3,
    'Q4_W2_MON_LONDON': 2,
    'Q4_W2_MON_NY_AM': 2,
    'Q4_W2_MON_NY_PM': 2,
    'Q4_W2_THU_ASIA': 2,
    'Q4_W2_THU_LONDON': 2,
    'Q4_W2_THU_NY_AM': 3,
    'Q4_W2_THU_NY_PM': 2,
    'Q4_W2_TUE_ASIA': 2,
    'Q4_W2_TUE_LONDON': 2,
    'Q4_W2_TUE_NY_AM': 1,
    'Q4_W2_TUE_NY_PM': 2,
    'Q4_W2_WED_ASIA': 3,
    'Q4_W2_WED_LONDON': 1,
    'Q4_W2_WED_NY_AM': 1,
    'Q4_W2_WED_NY_PM': 1,
    'Q4_W3_FRI_ASIA': 2,
    'Q4_W3_FRI_LONDON': 2,
    'Q4_W3_FRI_NY_AM': 3,
    'Q4_W3_FRI_NY_PM': 1,
    'Q4_W3_MON_ASIA': 2,
    'Q4_W3_MON_LONDON': 2,
    'Q4_W3_MON_NY_AM': 2,
    'Q4_W3_MON_NY_PM': 2,
    'Q4_W3_THU_ASIA': 2,
    'Q4_W3_THU_LONDON': 3,
    'Q4_W3_THU_NY_AM': 3,
    'Q4_W3_THU_NY_PM': 3,
    'Q4_W3_TUE_ASIA': 3,
    'Q4_W3_TUE_LONDON': 2,
    'Q4_W3_TUE_NY_AM': 1,
    'Q4_W3_TUE_NY_PM': 2,
    'Q4_W3_WED_ASIA': 1,
    'Q4_W3_WED_LONDON': 2,
    'Q4_W3_WED_NY_AM': 1,
    'Q4_W3_WED_NY_PM': 2,
    'Q4_W4_FRI_ASIA': 2,
    'Q4_W4_FRI_LONDON': 2,
    'Q4_W4_FRI_NY_AM': 2,
    'Q4_W4_FRI_NY_PM': 2,
    'Q4_W4_MON_ASIA': 3,
    'Q4_W4_MON_LONDON': 1,
    'Q4_W4_MON_NY_AM': 2,
    'Q4_W4_MON_NY_PM': 2,
    'Q4_W4_THU_ASIA': 2,
    'Q4_W4_THU_LONDON': 2,
    'Q4_W4_THU_NY_AM': 3,
    'Q4_W4_THU_NY_PM': 1,
    'Q4_W4_TUE_ASIA': 2,
    'Q4_W4_TUE_LONDON': 3,
    'Q4_W4_TUE_NY_AM': 1,
    'Q4_W4_TUE_NY_PM': 2,
    'Q4_W4_WED_ASIA': 3,
    'Q4_W4_WED_LONDON': 1,
    'Q4_W4_WED_NY_AM': 2,
    'Q4_W4_WED_NY_PM': 2,
}

# ============================================================
# SL/TP PARAMETERS - All combinations
# ============================================================
PARAMS = {
    'Q1_W1_FRI_ASIA': {
        'LONG': {'sl': 1.52, 'tp': 2.43, 'sl_mult': 2.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.52, 'tp': 2.43, 'sl_mult': 2.5, 'tp_mult': 4.0},
    },
    'Q1_W1_FRI_LONDON': {
        'LONG': {'sl': 3.38, 'tp': 3.86, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 3.38, 'tp': 3.86, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q1_W1_FRI_NY_AM': {
        'LONG': {'sl': 8.68, 'tp': 14.46, 'sl_mult': 3.0, 'tp_mult': 5.0},
        'SHORT': {'sl': 8.68, 'tp': 14.46, 'sl_mult': 3.0, 'tp_mult': 5.0},
    },
    'Q1_W1_FRI_NY_PM': {
        'LONG': {'sl': 6.94, 'tp': 7.93, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 6.94, 'tp': 7.93, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q1_W1_MON_ASIA': {
        'LONG': {'sl': 1.56, 'tp': 2.50, 'sl_mult': 2.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.56, 'tp': 2.50, 'sl_mult': 2.5, 'tp_mult': 4.0},
    },
    'Q1_W1_MON_LONDON': {
        'LONG': {'sl': 1.63, 'tp': 2.72, 'sl_mult': 1.5, 'tp_mult': 2.5},
        'SHORT': {'sl': 1.63, 'tp': 2.72, 'sl_mult': 1.5, 'tp_mult': 2.5},
    },
    'Q1_W1_MON_NY_AM': {
        'LONG': {'sl': 7.00, 'tp': 8.00, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 7.00, 'tp': 8.00, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q1_W1_MON_NY_PM': {
        'LONG': {'sl': 7.06, 'tp': 8.07, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 7.06, 'tp': 8.07, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q1_W1_THU_ASIA': {
        'LONG': {'sl': 1.52, 'tp': 2.43, 'sl_mult': 2.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.52, 'tp': 2.43, 'sl_mult': 2.5, 'tp_mult': 4.0},
    },
    'Q1_W1_THU_LONDON': {
        'LONG': {'sl': 2.86, 'tp': 3.43, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 2.86, 'tp': 3.43, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q1_W1_THU_NY_AM': {
        'LONG': {'sl': 4.93, 'tp': 7.39, 'sl_mult': 2.0, 'tp_mult': 3.0},
        'SHORT': {'sl': 4.93, 'tp': 7.39, 'sl_mult': 2.0, 'tp_mult': 3.0},
    },
    'Q1_W1_THU_NY_PM': {
        'LONG': {'sl': 3.03, 'tp': 6.05, 'sl_mult': 1.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 3.03, 'tp': 6.05, 'sl_mult': 1.5, 'tp_mult': 3.0},
    },
    'Q1_W1_TUE_ASIA': {
        'LONG': {'sl': 1.29, 'tp': 1.93, 'sl_mult': 2.0, 'tp_mult': 3.0},
        'SHORT': {'sl': 1.29, 'tp': 1.93, 'sl_mult': 2.0, 'tp_mult': 3.0},
    },
    'Q1_W1_TUE_LONDON': {
        'LONG': {'sl': 2.68, 'tp': 5.36, 'sl_mult': 2.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 2.68, 'tp': 5.36, 'sl_mult': 2.5, 'tp_mult': 5.0},
    },
    'Q1_W1_TUE_NY_AM': {
        'LONG': {'sl': 3.51, 'tp': 5.85, 'sl_mult': 1.5, 'tp_mult': 2.5},
        'SHORT': {'sl': 3.51, 'tp': 5.85, 'sl_mult': 1.5, 'tp_mult': 2.5},
    },
    'Q1_W1_TUE_NY_PM': {
        'LONG': {'sl': 6.00, 'tp': 10.00, 'sl_mult': 3.0, 'tp_mult': 5.0},
        'SHORT': {'sl': 6.00, 'tp': 10.00, 'sl_mult': 3.0, 'tp_mult': 5.0},
    },
    'Q1_W1_WED_ASIA': {
        'LONG': {'sl': 2.31, 'tp': 2.64, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 2.31, 'tp': 2.64, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q1_W1_WED_LONDON': {
        'LONG': {'sl': 2.79, 'tp': 3.71, 'sl_mult': 3.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 2.79, 'tp': 3.71, 'sl_mult': 3.0, 'tp_mult': 4.0},
    },
    'Q1_W1_WED_NY_AM': {
        'LONG': {'sl': 7.75, 'tp': 8.86, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 7.75, 'tp': 8.86, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q1_W1_WED_NY_PM': {
        'LONG': {'sl': 4.55, 'tp': 5.46, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 4.55, 'tp': 5.46, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q1_W2_FRI_ASIA': {
        'LONG': {'sl': 1.32, 'tp': 1.98, 'sl_mult': 2.0, 'tp_mult': 3.0},
        'SHORT': {'sl': 1.32, 'tp': 1.98, 'sl_mult': 2.0, 'tp_mult': 3.0},
    },
    'Q1_W2_FRI_LONDON': {
        'LONG': {'sl': 3.08, 'tp': 3.70, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 3.08, 'tp': 3.70, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q1_W2_FRI_NY_AM': {
        'LONG': {'sl': 6.52, 'tp': 7.82, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 6.52, 'tp': 7.82, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q1_W2_FRI_NY_PM': {
        'LONG': {'sl': 3.86, 'tp': 4.82, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 3.86, 'tp': 4.82, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q1_W2_MON_ASIA': {
        'LONG': {'sl': 1.88, 'tp': 3.75, 'sl_mult': 3.0, 'tp_mult': 6.0},
        'SHORT': {'sl': 1.88, 'tp': 3.75, 'sl_mult': 3.0, 'tp_mult': 6.0},
    },
    'Q1_W2_MON_LONDON': {
        'LONG': {'sl': 4.12, 'tp': 4.71, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 4.12, 'tp': 4.71, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q1_W2_MON_NY_AM': {
        'LONG': {'sl': 7.56, 'tp': 12.96, 'sl_mult': 3.5, 'tp_mult': 6.0},
        'SHORT': {'sl': 7.56, 'tp': 12.96, 'sl_mult': 3.5, 'tp_mult': 6.0},
    },
    'Q1_W2_MON_NY_PM': {
        'LONG': {'sl': 4.55, 'tp': 5.46, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 4.55, 'tp': 5.46, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q1_W2_THU_ASIA': {
        'LONG': {'sl': 2.25, 'tp': 3.21, 'sl_mult': 3.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 2.25, 'tp': 3.21, 'sl_mult': 3.5, 'tp_mult': 5.0},
    },
    'Q1_W2_THU_LONDON': {
        'LONG': {'sl': 1.79, 'tp': 2.68, 'sl_mult': 2.0, 'tp_mult': 3.0},
        'SHORT': {'sl': 1.79, 'tp': 2.68, 'sl_mult': 2.0, 'tp_mult': 3.0},
    },
    'Q1_W2_THU_NY_AM': {
        'LONG': {'sl': 9.12, 'tp': 13.04, 'sl_mult': 3.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 9.12, 'tp': 13.04, 'sl_mult': 3.5, 'tp_mult': 5.0},
    },
    'Q1_W2_THU_NY_PM': {
        'LONG': {'sl': 7.62, 'tp': 8.71, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 7.62, 'tp': 8.71, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q1_W2_TUE_ASIA': {
        'LONG': {'sl': 1.11, 'tp': 2.21, 'sl_mult': 2.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.11, 'tp': 2.21, 'sl_mult': 2.0, 'tp_mult': 4.0},
    },
    'Q1_W2_TUE_LONDON': {
        'LONG': {'sl': 3.69, 'tp': 4.21, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 3.69, 'tp': 4.21, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q1_W2_TUE_NY_AM': {
        'LONG': {'sl': 8.52, 'tp': 14.20, 'sl_mult': 3.0, 'tp_mult': 5.0},
        'SHORT': {'sl': 8.52, 'tp': 14.20, 'sl_mult': 3.0, 'tp_mult': 5.0},
    },
    'Q1_W2_TUE_NY_PM': {
        'LONG': {'sl': 5.18, 'tp': 6.21, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 5.18, 'tp': 6.21, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q1_W2_WED_ASIA': {
        'LONG': {'sl': 1.81, 'tp': 2.59, 'sl_mult': 3.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 1.81, 'tp': 2.59, 'sl_mult': 3.5, 'tp_mult': 5.0},
    },
    'Q1_W2_WED_LONDON': {
        'LONG': {'sl': 2.79, 'tp': 3.71, 'sl_mult': 3.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 2.79, 'tp': 3.71, 'sl_mult': 3.0, 'tp_mult': 4.0},
    },
    'Q1_W2_WED_NY_AM': {
        'LONG': {'sl': 8.44, 'tp': 9.64, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 8.44, 'tp': 9.64, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q1_W2_WED_NY_PM': {
        'LONG': {'sl': 3.79, 'tp': 5.68, 'sl_mult': 2.0, 'tp_mult': 3.0},
        'SHORT': {'sl': 3.79, 'tp': 5.68, 'sl_mult': 2.0, 'tp_mult': 3.0},
    },
    'Q1_W3_FRI_ASIA': {
        'LONG': {'sl': 0.83, 'tp': 1.66, 'sl_mult': 1.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 0.83, 'tp': 1.66, 'sl_mult': 1.5, 'tp_mult': 3.0},
    },
    'Q1_W3_FRI_LONDON': {
        'LONG': {'sl': 3.50, 'tp': 4.00, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 3.50, 'tp': 4.00, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q1_W3_FRI_NY_AM': {
        'LONG': {'sl': 4.93, 'tp': 9.86, 'sl_mult': 2.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 4.93, 'tp': 9.86, 'sl_mult': 2.0, 'tp_mult': 4.0},
    },
    'Q1_W3_FRI_NY_PM': {
        'LONG': {'sl': 5.00, 'tp': 8.00, 'sl_mult': 2.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 5.00, 'tp': 8.00, 'sl_mult': 2.5, 'tp_mult': 4.0},
    },
    'Q1_W3_MON_ASIA': {
        'LONG': {'sl': 1.52, 'tp': 2.43, 'sl_mult': 2.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.52, 'tp': 2.43, 'sl_mult': 2.5, 'tp_mult': 4.0},
    },
    'Q1_W3_MON_LONDON': {
        'LONG': {'sl': 2.57, 'tp': 3.43, 'sl_mult': 3.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 2.57, 'tp': 3.43, 'sl_mult': 3.0, 'tp_mult': 4.0},
    },
    'Q1_W3_MON_NY_AM': {
        'LONG': {'sl': 1.29, 'tp': 1.71, 'sl_mult': 1.5, 'tp_mult': 2.0},
        'SHORT': {'sl': 1.29, 'tp': 1.71, 'sl_mult': 1.5, 'tp_mult': 2.0},
    },
    'Q1_W3_MON_NY_PM': {
        'LONG': {'sl': 3.18, 'tp': 3.97, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 3.18, 'tp': 3.97, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q1_W3_THU_ASIA': {
        'LONG': {'sl': 2.06, 'tp': 2.95, 'sl_mult': 3.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 2.06, 'tp': 2.95, 'sl_mult': 3.5, 'tp_mult': 5.0},
    },
    'Q1_W3_THU_LONDON': {
        'LONG': {'sl': 1.53, 'tp': 2.54, 'sl_mult': 1.5, 'tp_mult': 2.5},
        'SHORT': {'sl': 1.53, 'tp': 2.54, 'sl_mult': 1.5, 'tp_mult': 2.5},
    },
    'Q1_W3_THU_NY_AM': {
        'LONG': {'sl': 8.62, 'tp': 9.86, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 8.62, 'tp': 9.86, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q1_W3_THU_NY_PM': {
        'LONG': {'sl': 3.89, 'tp': 4.87, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 3.89, 'tp': 4.87, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q1_W3_TUE_ASIA': {
        'LONG': {'sl': 1.94, 'tp': 2.21, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.94, 'tp': 2.21, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q1_W3_TUE_LONDON': {
        'LONG': {'sl': 4.06, 'tp': 4.64, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 4.06, 'tp': 4.64, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q1_W3_TUE_NY_AM': {
        'LONG': {'sl': 5.27, 'tp': 6.32, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 5.27, 'tp': 6.32, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q1_W3_TUE_NY_PM': {
        'LONG': {'sl': 3.29, 'tp': 4.11, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 3.29, 'tp': 4.11, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q1_W3_WED_ASIA': {
        'LONG': {'sl': 1.52, 'tp': 2.43, 'sl_mult': 2.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.52, 'tp': 2.43, 'sl_mult': 2.5, 'tp_mult': 4.0},
    },
    'Q1_W3_WED_LONDON': {
        'LONG': {'sl': 2.79, 'tp': 3.71, 'sl_mult': 3.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 2.79, 'tp': 3.71, 'sl_mult': 3.0, 'tp_mult': 4.0},
    },
    'Q1_W3_WED_NY_AM': {
        'LONG': {'sl': 7.69, 'tp': 8.79, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 7.69, 'tp': 8.79, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q1_W3_WED_NY_PM': {
        'LONG': {'sl': 2.81, 'tp': 3.75, 'sl_mult': 1.5, 'tp_mult': 2.0},
        'SHORT': {'sl': 2.81, 'tp': 3.75, 'sl_mult': 1.5, 'tp_mult': 2.0},
    },
    'Q1_W4_FRI_ASIA': {
        'LONG': {'sl': 0.80, 'tp': 1.61, 'sl_mult': 1.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 0.80, 'tp': 1.61, 'sl_mult': 1.5, 'tp_mult': 3.0},
    },
    'Q1_W4_FRI_LONDON': {
        'LONG': {'sl': 3.06, 'tp': 3.50, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 3.06, 'tp': 3.50, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q1_W4_FRI_NY_AM': {
        'LONG': {'sl': 5.40, 'tp': 12.96, 'sl_mult': 2.5, 'tp_mult': 6.0},
        'SHORT': {'sl': 5.40, 'tp': 12.96, 'sl_mult': 2.5, 'tp_mult': 6.0},
    },
    'Q1_W4_FRI_NY_PM': {
        'LONG': {'sl': 3.57, 'tp': 10.71, 'sl_mult': 2.0, 'tp_mult': 6.0},
        'SHORT': {'sl': 3.57, 'tp': 10.71, 'sl_mult': 2.0, 'tp_mult': 6.0},
    },
    'Q1_W4_MON_ASIA': {
        'LONG': {'sl': 0.83, 'tp': 1.66, 'sl_mult': 1.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 0.83, 'tp': 1.66, 'sl_mult': 1.5, 'tp_mult': 3.0},
    },
    'Q1_W4_MON_LONDON': {
        'LONG': {'sl': 3.50, 'tp': 4.00, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 3.50, 'tp': 4.00, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q1_W4_MON_NY_AM': {
        'LONG': {'sl': 6.94, 'tp': 7.93, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 6.94, 'tp': 7.93, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q1_W4_MON_NY_PM': {
        'LONG': {'sl': 3.57, 'tp': 4.46, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 3.57, 'tp': 4.46, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q1_W4_THU_ASIA': {
        'LONG': {'sl': 1.77, 'tp': 2.36, 'sl_mult': 3.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.77, 'tp': 2.36, 'sl_mult': 3.0, 'tp_mult': 4.0},
    },
    'Q1_W4_THU_LONDON': {
        'LONG': {'sl': 3.31, 'tp': 3.79, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 3.31, 'tp': 3.79, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q1_W4_THU_NY_AM': {
        'LONG': {'sl': 3.16, 'tp': 4.21, 'sl_mult': 1.5, 'tp_mult': 2.0},
        'SHORT': {'sl': 3.16, 'tp': 4.21, 'sl_mult': 1.5, 'tp_mult': 2.0},
    },
    'Q1_W4_THU_NY_PM': {
        'LONG': {'sl': 3.57, 'tp': 4.46, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 3.57, 'tp': 4.46, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q1_W4_TUE_ASIA': {
        'LONG': {'sl': 1.75, 'tp': 2.00, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.75, 'tp': 2.00, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q1_W4_TUE_LONDON': {
        'LONG': {'sl': 2.79, 'tp': 4.64, 'sl_mult': 3.0, 'tp_mult': 5.0},
        'SHORT': {'sl': 2.79, 'tp': 4.64, 'sl_mult': 3.0, 'tp_mult': 5.0},
    },
    'Q1_W4_TUE_NY_AM': {
        'LONG': {'sl': 4.38, 'tp': 5.25, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 4.38, 'tp': 5.25, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q1_W4_TUE_NY_PM': {
        'LONG': {'sl': 5.31, 'tp': 7.59, 'sl_mult': 3.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 5.31, 'tp': 7.59, 'sl_mult': 3.5, 'tp_mult': 5.0},
    },
    'Q1_W4_WED_ASIA': {
        'LONG': {'sl': 1.34, 'tp': 2.68, 'sl_mult': 2.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 1.34, 'tp': 2.68, 'sl_mult': 2.5, 'tp_mult': 5.0},
    },
    'Q1_W4_WED_LONDON': {
        'LONG': {'sl': 1.31, 'tp': 1.75, 'sl_mult': 1.5, 'tp_mult': 2.0},
        'SHORT': {'sl': 1.31, 'tp': 1.75, 'sl_mult': 1.5, 'tp_mult': 2.0},
    },
    'Q1_W4_WED_NY_AM': {
        'LONG': {'sl': 3.57, 'tp': 4.46, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 3.57, 'tp': 4.46, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q1_W4_WED_NY_PM': {
        'LONG': {'sl': 3.54, 'tp': 4.42, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 3.54, 'tp': 4.42, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q2_W1_FRI_ASIA': {
        'LONG': {'sl': 1.43, 'tp': 1.71, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 1.43, 'tp': 1.71, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q2_W1_FRI_LONDON': {
        'LONG': {'sl': 3.12, 'tp': 4.46, 'sl_mult': 3.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 3.12, 'tp': 4.46, 'sl_mult': 3.5, 'tp_mult': 5.0},
    },
    'Q2_W1_FRI_NY_AM': {
        'LONG': {'sl': 4.23, 'tp': 8.46, 'sl_mult': 1.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 4.23, 'tp': 8.46, 'sl_mult': 1.5, 'tp_mult': 3.0},
    },
    'Q2_W1_FRI_NY_PM': {
        'LONG': {'sl': 3.79, 'tp': 4.73, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 3.79, 'tp': 4.73, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q2_W1_MON_ASIA': {
        'LONG': {'sl': 0.83, 'tp': 1.66, 'sl_mult': 1.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 0.83, 'tp': 1.66, 'sl_mult': 1.5, 'tp_mult': 3.0},
    },
    'Q2_W1_MON_LONDON': {
        'LONG': {'sl': 3.06, 'tp': 3.50, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 3.06, 'tp': 3.50, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q2_W1_MON_NY_AM': {
        'LONG': {'sl': 4.78, 'tp': 7.64, 'sl_mult': 2.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 4.78, 'tp': 7.64, 'sl_mult': 2.5, 'tp_mult': 4.0},
    },
    'Q2_W1_MON_NY_PM': {
        'LONG': {'sl': 2.36, 'tp': 4.71, 'sl_mult': 1.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 2.36, 'tp': 4.71, 'sl_mult': 1.5, 'tp_mult': 3.0},
    },
    'Q2_W1_THU_ASIA': {
        'LONG': {'sl': 2.19, 'tp': 2.50, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 2.19, 'tp': 2.50, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q2_W1_THU_LONDON': {
        'LONG': {'sl': 1.58, 'tp': 4.21, 'sl_mult': 1.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.58, 'tp': 4.21, 'sl_mult': 1.5, 'tp_mult': 4.0},
    },
    'Q2_W1_THU_NY_AM': {
        'LONG': {'sl': 8.06, 'tp': 9.21, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 8.06, 'tp': 9.21, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q2_W1_THU_NY_PM': {
        'LONG': {'sl': 6.59, 'tp': 13.18, 'sl_mult': 3.0, 'tp_mult': 6.0},
        'SHORT': {'sl': 6.59, 'tp': 13.18, 'sl_mult': 3.0, 'tp_mult': 6.0},
    },
    'Q2_W1_TUE_ASIA': {
        'LONG': {'sl': 1.88, 'tp': 2.14, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.88, 'tp': 2.14, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q2_W1_TUE_LONDON': {
        'LONG': {'sl': 3.05, 'tp': 4.07, 'sl_mult': 3.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 3.05, 'tp': 4.07, 'sl_mult': 3.0, 'tp_mult': 4.0},
    },
    'Q2_W1_TUE_NY_AM': {
        'LONG': {'sl': 4.91, 'tp': 7.86, 'sl_mult': 2.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 4.91, 'tp': 7.86, 'sl_mult': 2.5, 'tp_mult': 4.0},
    },
    'Q2_W1_TUE_NY_PM': {
        'LONG': {'sl': 3.57, 'tp': 4.46, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 3.57, 'tp': 4.46, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q2_W1_WED_ASIA': {
        'LONG': {'sl': 1.52, 'tp': 2.43, 'sl_mult': 2.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.52, 'tp': 2.43, 'sl_mult': 2.5, 'tp_mult': 4.0},
    },
    'Q2_W1_WED_LONDON': {
        'LONG': {'sl': 2.28, 'tp': 2.73, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 2.28, 'tp': 2.73, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q2_W1_WED_NY_AM': {
        'LONG': {'sl': 5.31, 'tp': 6.38, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 5.31, 'tp': 6.38, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q2_W1_WED_NY_PM': {
        'LONG': {'sl': 6.06, 'tp': 6.93, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 6.06, 'tp': 6.93, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q2_W2_FRI_ASIA': {
        'LONG': {'sl': 1.62, 'tp': 2.32, 'sl_mult': 3.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 1.62, 'tp': 2.32, 'sl_mult': 3.5, 'tp_mult': 5.0},
    },
    'Q2_W2_FRI_LONDON': {
        'LONG': {'sl': 2.18, 'tp': 2.72, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 2.18, 'tp': 2.72, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q2_W2_FRI_NY_AM': {
        'LONG': {'sl': 4.54, 'tp': 11.34, 'sl_mult': 2.0, 'tp_mult': 5.0},
        'SHORT': {'sl': 4.54, 'tp': 11.34, 'sl_mult': 2.0, 'tp_mult': 5.0},
    },
    'Q2_W2_FRI_NY_PM': {
        'LONG': {'sl': 6.25, 'tp': 7.14, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 6.25, 'tp': 7.14, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q2_W2_MON_ASIA': {
        'LONG': {'sl': 1.62, 'tp': 1.86, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.62, 'tp': 1.86, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q2_W2_MON_LONDON': {
        'LONG': {'sl': 1.79, 'tp': 2.68, 'sl_mult': 2.0, 'tp_mult': 3.0},
        'SHORT': {'sl': 1.79, 'tp': 2.68, 'sl_mult': 2.0, 'tp_mult': 3.0},
    },
    'Q2_W2_MON_NY_AM': {
        'LONG': {'sl': 5.04, 'tp': 6.71, 'sl_mult': 3.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 5.04, 'tp': 6.71, 'sl_mult': 3.0, 'tp_mult': 4.0},
    },
    'Q2_W2_MON_NY_PM': {
        'LONG': {'sl': 4.94, 'tp': 5.64, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 4.94, 'tp': 5.64, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q2_W2_THU_ASIA': {
        'LONG': {'sl': 1.61, 'tp': 3.21, 'sl_mult': 3.0, 'tp_mult': 6.0},
        'SHORT': {'sl': 1.61, 'tp': 3.21, 'sl_mult': 3.0, 'tp_mult': 6.0},
    },
    'Q2_W2_THU_LONDON': {
        'LONG': {'sl': 3.56, 'tp': 4.07, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 3.56, 'tp': 4.07, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q2_W2_THU_NY_AM': {
        'LONG': {'sl': 8.12, 'tp': 11.61, 'sl_mult': 3.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 8.12, 'tp': 11.61, 'sl_mult': 3.5, 'tp_mult': 5.0},
    },
    'Q2_W2_THU_NY_PM': {
        'LONG': {'sl': 5.69, 'tp': 6.50, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 5.69, 'tp': 6.50, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q2_W2_TUE_ASIA': {
        'LONG': {'sl': 1.56, 'tp': 2.68, 'sl_mult': 3.5, 'tp_mult': 6.0},
        'SHORT': {'sl': 1.56, 'tp': 2.68, 'sl_mult': 3.5, 'tp_mult': 6.0},
    },
    'Q2_W2_TUE_LONDON': {
        'LONG': {'sl': 3.19, 'tp': 5.46, 'sl_mult': 3.5, 'tp_mult': 6.0},
        'SHORT': {'sl': 3.19, 'tp': 5.46, 'sl_mult': 3.5, 'tp_mult': 6.0},
    },
    'Q2_W2_TUE_NY_AM': {
        'LONG': {'sl': 2.84, 'tp': 3.79, 'sl_mult': 1.5, 'tp_mult': 2.0},
        'SHORT': {'sl': 2.84, 'tp': 3.79, 'sl_mult': 1.5, 'tp_mult': 2.0},
    },
    'Q2_W2_TUE_NY_PM': {
        'LONG': {'sl': 5.50, 'tp': 6.29, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 5.50, 'tp': 6.29, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q2_W2_WED_ASIA': {
        'LONG': {'sl': 1.66, 'tp': 2.21, 'sl_mult': 3.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.66, 'tp': 2.21, 'sl_mult': 3.0, 'tp_mult': 4.0},
    },
    'Q2_W2_WED_LONDON': {
        'LONG': {'sl': 2.81, 'tp': 3.21, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 2.81, 'tp': 3.21, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q2_W2_WED_NY_AM': {
        'LONG': {'sl': 6.96, 'tp': 11.61, 'sl_mult': 3.0, 'tp_mult': 5.0},
        'SHORT': {'sl': 6.96, 'tp': 11.61, 'sl_mult': 3.0, 'tp_mult': 5.0},
    },
    'Q2_W2_WED_NY_PM': {
        'LONG': {'sl': 7.56, 'tp': 8.64, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 7.56, 'tp': 8.64, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q2_W3_FRI_ASIA': {
        'LONG': {'sl': 1.81, 'tp': 2.59, 'sl_mult': 3.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 1.81, 'tp': 2.59, 'sl_mult': 3.5, 'tp_mult': 5.0},
    },
    'Q2_W3_FRI_LONDON': {
        'LONG': {'sl': 3.50, 'tp': 5.00, 'sl_mult': 3.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 3.50, 'tp': 5.00, 'sl_mult': 3.5, 'tp_mult': 5.0},
    },
    'Q2_W3_FRI_NY_AM': {
        'LONG': {'sl': 4.36, 'tp': 5.45, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 4.36, 'tp': 5.45, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q2_W3_FRI_NY_PM': {
        'LONG': {'sl': 3.36, 'tp': 4.20, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 3.36, 'tp': 4.20, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q2_W3_MON_ASIA': {
        'LONG': {'sl': 1.77, 'tp': 2.95, 'sl_mult': 3.0, 'tp_mult': 5.0},
        'SHORT': {'sl': 1.77, 'tp': 2.95, 'sl_mult': 3.0, 'tp_mult': 5.0},
    },
    'Q2_W3_MON_LONDON': {
        'LONG': {'sl': 2.79, 'tp': 3.71, 'sl_mult': 3.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 2.79, 'tp': 3.71, 'sl_mult': 3.0, 'tp_mult': 4.0},
    },
    'Q2_W3_MON_NY_AM': {
        'LONG': {'sl': 4.33, 'tp': 5.20, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 4.33, 'tp': 5.20, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q2_W3_MON_NY_PM': {
        'LONG': {'sl': 4.02, 'tp': 4.82, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 4.02, 'tp': 4.82, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q2_W3_THU_ASIA': {
        'LONG': {'sl': 1.94, 'tp': 2.21, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.94, 'tp': 2.21, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q2_W3_THU_LONDON': {
        'LONG': {'sl': 2.46, 'tp': 2.95, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 2.46, 'tp': 2.95, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q2_W3_THU_NY_AM': {
        'LONG': {'sl': 7.00, 'tp': 8.00, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 7.00, 'tp': 8.00, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q2_W3_THU_NY_PM': {
        'LONG': {'sl': 7.19, 'tp': 8.21, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 7.19, 'tp': 8.21, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q2_W3_TUE_ASIA': {
        'LONG': {'sl': 1.88, 'tp': 3.21, 'sl_mult': 3.5, 'tp_mult': 6.0},
        'SHORT': {'sl': 1.88, 'tp': 3.21, 'sl_mult': 3.5, 'tp_mult': 6.0},
    },
    'Q2_W3_TUE_LONDON': {
        'LONG': {'sl': 3.31, 'tp': 5.68, 'sl_mult': 3.5, 'tp_mult': 6.0},
        'SHORT': {'sl': 3.31, 'tp': 5.68, 'sl_mult': 3.5, 'tp_mult': 6.0},
    },
    'Q2_W3_TUE_NY_AM': {
        'LONG': {'sl': 7.12, 'tp': 8.14, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 7.12, 'tp': 8.14, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q2_W3_TUE_NY_PM': {
        'LONG': {'sl': 3.14, 'tp': 3.93, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 3.14, 'tp': 3.93, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q2_W3_WED_ASIA': {
        'LONG': {'sl': 2.00, 'tp': 3.43, 'sl_mult': 3.5, 'tp_mult': 6.0},
        'SHORT': {'sl': 2.00, 'tp': 3.43, 'sl_mult': 3.5, 'tp_mult': 6.0},
    },
    'Q2_W3_WED_LONDON': {
        'LONG': {'sl': 3.38, 'tp': 3.86, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 3.38, 'tp': 3.86, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q2_W3_WED_NY_AM': {
        'LONG': {'sl': 4.78, 'tp': 7.64, 'sl_mult': 2.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 4.78, 'tp': 7.64, 'sl_mult': 2.5, 'tp_mult': 4.0},
    },
    'Q2_W3_WED_NY_PM': {
        'LONG': {'sl': 6.06, 'tp': 6.93, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 6.06, 'tp': 6.93, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q2_W4_FRI_ASIA': {
        'LONG': {'sl': 1.77, 'tp': 2.95, 'sl_mult': 3.0, 'tp_mult': 5.0},
        'SHORT': {'sl': 1.77, 'tp': 2.95, 'sl_mult': 3.0, 'tp_mult': 5.0},
    },
    'Q2_W4_FRI_LONDON': {
        'LONG': {'sl': 2.79, 'tp': 3.71, 'sl_mult': 3.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 2.79, 'tp': 3.71, 'sl_mult': 3.0, 'tp_mult': 4.0},
    },
    'Q2_W4_FRI_NY_AM': {
        'LONG': {'sl': 7.02, 'tp': 9.36, 'sl_mult': 3.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 7.02, 'tp': 9.36, 'sl_mult': 3.0, 'tp_mult': 4.0},
    },
    'Q2_W4_FRI_NY_PM': {
        'LONG': {'sl': 2.52, 'tp': 4.20, 'sl_mult': 1.5, 'tp_mult': 2.5},
        'SHORT': {'sl': 2.52, 'tp': 4.20, 'sl_mult': 1.5, 'tp_mult': 2.5},
    },
    'Q2_W4_MON_ASIA': {
        'LONG': {'sl': 1.11, 'tp': 2.21, 'sl_mult': 2.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.11, 'tp': 2.21, 'sl_mult': 2.0, 'tp_mult': 4.0},
    },
    'Q2_W4_MON_LONDON': {
        'LONG': {'sl': 2.05, 'tp': 2.46, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 2.05, 'tp': 2.46, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q2_W4_MON_NY_AM': {
        'LONG': {'sl': 5.44, 'tp': 6.21, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 5.44, 'tp': 6.21, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q2_W4_MON_NY_PM': {
        'LONG': {'sl': 2.44, 'tp': 3.25, 'sl_mult': 1.5, 'tp_mult': 2.0},
        'SHORT': {'sl': 2.44, 'tp': 3.25, 'sl_mult': 1.5, 'tp_mult': 2.0},
    },
    'Q2_W4_THU_ASIA': {
        'LONG': {'sl': 1.52, 'tp': 2.43, 'sl_mult': 2.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.52, 'tp': 2.43, 'sl_mult': 2.5, 'tp_mult': 4.0},
    },
    'Q2_W4_THU_LONDON': {
        'LONG': {'sl': 1.79, 'tp': 2.23, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 1.79, 'tp': 2.23, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q2_W4_THU_NY_AM': {
        'LONG': {'sl': 8.06, 'tp': 9.21, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 8.06, 'tp': 9.21, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q2_W4_THU_NY_PM': {
        'LONG': {'sl': 6.06, 'tp': 10.39, 'sl_mult': 3.5, 'tp_mult': 6.0},
        'SHORT': {'sl': 6.06, 'tp': 10.39, 'sl_mult': 3.5, 'tp_mult': 6.0},
    },
    'Q2_W4_TUE_ASIA': {
        'LONG': {'sl': 0.86, 'tp': 1.71, 'sl_mult': 1.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 0.86, 'tp': 1.71, 'sl_mult': 1.5, 'tp_mult': 3.0},
    },
    'Q2_W4_TUE_LONDON': {
        'LONG': {'sl': 3.56, 'tp': 4.07, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 3.56, 'tp': 4.07, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q2_W4_TUE_NY_AM': {
        'LONG': {'sl': 7.06, 'tp': 10.09, 'sl_mult': 3.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 7.06, 'tp': 10.09, 'sl_mult': 3.5, 'tp_mult': 5.0},
    },
    'Q2_W4_TUE_NY_PM': {
        'LONG': {'sl': 4.38, 'tp': 5.25, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 4.38, 'tp': 5.25, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q2_W4_WED_ASIA': {
        'LONG': {'sl': 1.93, 'tp': 3.21, 'sl_mult': 3.0, 'tp_mult': 5.0},
        'SHORT': {'sl': 1.93, 'tp': 3.21, 'sl_mult': 3.0, 'tp_mult': 5.0},
    },
    'Q2_W4_WED_LONDON': {
        'LONG': {'sl': 2.50, 'tp': 3.00, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 2.50, 'tp': 3.00, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q2_W4_WED_NY_AM': {
        'LONG': {'sl': 6.05, 'tp': 8.07, 'sl_mult': 3.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 6.05, 'tp': 8.07, 'sl_mult': 3.0, 'tp_mult': 4.0},
    },
    'Q2_W4_WED_NY_PM': {
        'LONG': {'sl': 3.64, 'tp': 7.29, 'sl_mult': 2.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 3.64, 'tp': 7.29, 'sl_mult': 2.0, 'tp_mult': 4.0},
    },
    'Q3_W1_FRI_ASIA': {
        'LONG': {'sl': 2.12, 'tp': 3.64, 'sl_mult': 3.5, 'tp_mult': 6.0},
        'SHORT': {'sl': 2.12, 'tp': 3.64, 'sl_mult': 3.5, 'tp_mult': 6.0},
    },
    'Q3_W1_FRI_LONDON': {
        'LONG': {'sl': 2.63, 'tp': 3.16, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 2.63, 'tp': 3.16, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q3_W1_FRI_NY_AM': {
        'LONG': {'sl': 7.93, 'tp': 10.57, 'sl_mult': 3.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 7.93, 'tp': 10.57, 'sl_mult': 3.0, 'tp_mult': 4.0},
    },
    'Q3_W1_FRI_NY_PM': {
        'LONG': {'sl': 6.19, 'tp': 10.61, 'sl_mult': 3.5, 'tp_mult': 6.0},
        'SHORT': {'sl': 6.19, 'tp': 10.61, 'sl_mult': 3.5, 'tp_mult': 6.0},
    },
    'Q3_W1_MON_ASIA': {
        'LONG': {'sl': 1.56, 'tp': 2.50, 'sl_mult': 2.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.56, 'tp': 2.50, 'sl_mult': 2.5, 'tp_mult': 4.0},
    },
    'Q3_W1_MON_LONDON': {
        'LONG': {'sl': 3.06, 'tp': 3.50, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 3.06, 'tp': 3.50, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q3_W1_MON_NY_AM': {
        'LONG': {'sl': 4.31, 'tp': 4.93, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 4.31, 'tp': 4.93, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q3_W1_MON_NY_PM': {
        'LONG': {'sl': 3.14, 'tp': 3.93, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 3.14, 'tp': 3.93, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q3_W1_THU_ASIA': {
        'LONG': {'sl': 1.77, 'tp': 2.95, 'sl_mult': 3.0, 'tp_mult': 5.0},
        'SHORT': {'sl': 1.77, 'tp': 2.95, 'sl_mult': 3.0, 'tp_mult': 5.0},
    },
    'Q3_W1_THU_LONDON': {
        'LONG': {'sl': 3.56, 'tp': 6.11, 'sl_mult': 3.5, 'tp_mult': 6.0},
        'SHORT': {'sl': 3.56, 'tp': 6.11, 'sl_mult': 3.5, 'tp_mult': 6.0},
    },
    'Q3_W1_THU_NY_AM': {
        'LONG': {'sl': 3.89, 'tp': 7.79, 'sl_mult': 2.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 3.89, 'tp': 7.79, 'sl_mult': 2.0, 'tp_mult': 4.0},
    },
    'Q3_W1_THU_NY_PM': {
        'LONG': {'sl': 3.27, 'tp': 4.90, 'sl_mult': 2.0, 'tp_mult': 3.0},
        'SHORT': {'sl': 3.27, 'tp': 4.90, 'sl_mult': 2.0, 'tp_mult': 3.0},
    },
    'Q3_W1_TUE_ASIA': {
        'LONG': {'sl': 1.56, 'tp': 2.50, 'sl_mult': 2.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.56, 'tp': 2.50, 'sl_mult': 2.5, 'tp_mult': 4.0},
    },
    'Q3_W1_TUE_LONDON': {
        'LONG': {'sl': 2.50, 'tp': 3.00, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 2.50, 'tp': 3.00, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q3_W1_TUE_NY_AM': {
        'LONG': {'sl': 7.94, 'tp': 9.07, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 7.94, 'tp': 9.07, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q3_W1_TUE_NY_PM': {
        'LONG': {'sl': 5.46, 'tp': 9.11, 'sl_mult': 3.0, 'tp_mult': 5.0},
        'SHORT': {'sl': 5.46, 'tp': 9.11, 'sl_mult': 3.0, 'tp_mult': 5.0},
    },
    'Q3_W1_WED_ASIA': {
        'LONG': {'sl': 1.32, 'tp': 1.98, 'sl_mult': 2.0, 'tp_mult': 3.0},
        'SHORT': {'sl': 1.32, 'tp': 1.98, 'sl_mult': 2.0, 'tp_mult': 3.0},
    },
    'Q3_W1_WED_LONDON': {
        'LONG': {'sl': 2.07, 'tp': 3.11, 'sl_mult': 2.0, 'tp_mult': 3.0},
        'SHORT': {'sl': 2.07, 'tp': 3.11, 'sl_mult': 2.0, 'tp_mult': 3.0},
    },
    'Q3_W1_WED_NY_AM': {
        'LONG': {'sl': 5.79, 'tp': 11.57, 'sl_mult': 3.0, 'tp_mult': 6.0},
        'SHORT': {'sl': 5.79, 'tp': 11.57, 'sl_mult': 3.0, 'tp_mult': 6.0},
    },
    'Q3_W1_WED_NY_PM': {
        'LONG': {'sl': 5.81, 'tp': 6.64, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 5.81, 'tp': 6.64, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q3_W2_FRI_ASIA': {
        'LONG': {'sl': 1.71, 'tp': 3.43, 'sl_mult': 3.0, 'tp_mult': 6.0},
        'SHORT': {'sl': 1.71, 'tp': 3.43, 'sl_mult': 3.0, 'tp_mult': 6.0},
    },
    'Q3_W2_FRI_LONDON': {
        'LONG': {'sl': 2.79, 'tp': 3.71, 'sl_mult': 3.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 2.79, 'tp': 3.71, 'sl_mult': 3.0, 'tp_mult': 4.0},
    },
    'Q3_W2_FRI_NY_AM': {
        'LONG': {'sl': 7.19, 'tp': 8.21, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 7.19, 'tp': 8.21, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q3_W2_FRI_NY_PM': {
        'LONG': {'sl': 5.50, 'tp': 7.86, 'sl_mult': 3.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 5.50, 'tp': 7.86, 'sl_mult': 3.5, 'tp_mult': 5.0},
    },
    'Q3_W2_MON_ASIA': {
        'LONG': {'sl': 0.86, 'tp': 1.71, 'sl_mult': 1.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 0.86, 'tp': 1.71, 'sl_mult': 1.5, 'tp_mult': 3.0},
    },
    'Q3_W2_MON_LONDON': {
        'LONG': {'sl': 2.68, 'tp': 4.46, 'sl_mult': 3.0, 'tp_mult': 5.0},
        'SHORT': {'sl': 2.68, 'tp': 4.46, 'sl_mult': 3.0, 'tp_mult': 5.0},
    },
    'Q3_W2_MON_NY_AM': {
        'LONG': {'sl': 6.12, 'tp': 8.75, 'sl_mult': 3.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 6.12, 'tp': 8.75, 'sl_mult': 3.5, 'tp_mult': 5.0},
    },
    'Q3_W2_MON_NY_PM': {
        'LONG': {'sl': 4.88, 'tp': 6.96, 'sl_mult': 3.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 4.88, 'tp': 6.96, 'sl_mult': 3.5, 'tp_mult': 5.0},
    },
    'Q3_W2_THU_ASIA': {
        'LONG': {'sl': 1.61, 'tp': 2.68, 'sl_mult': 3.0, 'tp_mult': 5.0},
        'SHORT': {'sl': 1.61, 'tp': 2.68, 'sl_mult': 3.0, 'tp_mult': 5.0},
    },
    'Q3_W2_THU_LONDON': {
        'LONG': {'sl': 1.79, 'tp': 2.14, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 1.79, 'tp': 2.14, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q3_W2_THU_NY_AM': {
        'LONG': {'sl': 8.62, 'tp': 12.32, 'sl_mult': 3.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 8.62, 'tp': 12.32, 'sl_mult': 3.5, 'tp_mult': 5.0},
    },
    'Q3_W2_THU_NY_PM': {
        'LONG': {'sl': 2.28, 'tp': 3.04, 'sl_mult': 1.5, 'tp_mult': 2.0},
        'SHORT': {'sl': 2.28, 'tp': 3.04, 'sl_mult': 1.5, 'tp_mult': 2.0},
    },
    'Q3_W2_TUE_ASIA': {
        'LONG': {'sl': 1.88, 'tp': 2.68, 'sl_mult': 3.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 1.88, 'tp': 2.68, 'sl_mult': 3.5, 'tp_mult': 5.0},
    },
    'Q3_W2_TUE_LONDON': {
        'LONG': {'sl': 1.79, 'tp': 2.23, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 1.79, 'tp': 2.23, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q3_W2_TUE_NY_AM': {
        'LONG': {'sl': 6.56, 'tp': 7.50, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 6.56, 'tp': 7.50, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q3_W2_TUE_NY_PM': {
        'LONG': {'sl': 4.88, 'tp': 5.57, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 4.88, 'tp': 5.57, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q3_W2_WED_ASIA': {
        'LONG': {'sl': 1.25, 'tp': 1.50, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 1.25, 'tp': 1.50, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q3_W2_WED_LONDON': {
        'LONG': {'sl': 1.57, 'tp': 1.96, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 1.57, 'tp': 1.96, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q3_W2_WED_NY_AM': {
        'LONG': {'sl': 6.16, 'tp': 12.32, 'sl_mult': 3.0, 'tp_mult': 6.0},
        'SHORT': {'sl': 6.16, 'tp': 12.32, 'sl_mult': 3.0, 'tp_mult': 6.0},
    },
    'Q3_W2_WED_NY_PM': {
        'LONG': {'sl': 2.36, 'tp': 3.93, 'sl_mult': 1.5, 'tp_mult': 2.5},
        'SHORT': {'sl': 2.36, 'tp': 3.93, 'sl_mult': 1.5, 'tp_mult': 2.5},
    },
    'Q3_W3_FRI_ASIA': {
        'LONG': {'sl': 1.94, 'tp': 2.21, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.94, 'tp': 2.21, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q3_W3_FRI_LONDON': {
        'LONG': {'sl': 2.79, 'tp': 3.71, 'sl_mult': 3.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 2.79, 'tp': 3.71, 'sl_mult': 3.0, 'tp_mult': 4.0},
    },
    'Q3_W3_FRI_NY_AM': {
        'LONG': {'sl': 5.31, 'tp': 6.38, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 5.31, 'tp': 6.38, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q3_W3_FRI_NY_PM': {
        'LONG': {'sl': 3.93, 'tp': 4.71, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 3.93, 'tp': 4.71, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q3_W3_MON_ASIA': {
        'LONG': {'sl': 1.56, 'tp': 2.68, 'sl_mult': 3.5, 'tp_mult': 6.0},
        'SHORT': {'sl': 1.56, 'tp': 2.68, 'sl_mult': 3.5, 'tp_mult': 6.0},
    },
    'Q3_W3_MON_LONDON': {
        'LONG': {'sl': 2.56, 'tp': 4.39, 'sl_mult': 3.5, 'tp_mult': 6.0},
        'SHORT': {'sl': 2.56, 'tp': 4.39, 'sl_mult': 3.5, 'tp_mult': 6.0},
    },
    'Q3_W3_MON_NY_AM': {
        'LONG': {'sl': 3.75, 'tp': 4.50, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 3.75, 'tp': 4.50, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q3_W3_MON_NY_PM': {
        'LONG': {'sl': 3.86, 'tp': 7.71, 'sl_mult': 3.0, 'tp_mult': 6.0},
        'SHORT': {'sl': 3.86, 'tp': 7.71, 'sl_mult': 3.0, 'tp_mult': 6.0},
    },
    'Q3_W3_THU_ASIA': {
        'LONG': {'sl': 1.56, 'tp': 2.50, 'sl_mult': 2.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.56, 'tp': 2.50, 'sl_mult': 2.5, 'tp_mult': 4.0},
    },
    'Q3_W3_THU_LONDON': {
        'LONG': {'sl': 2.04, 'tp': 3.05, 'sl_mult': 2.0, 'tp_mult': 3.0},
        'SHORT': {'sl': 2.04, 'tp': 3.05, 'sl_mult': 2.0, 'tp_mult': 3.0},
    },
    'Q3_W3_THU_NY_AM': {
        'LONG': {'sl': 7.38, 'tp': 8.43, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 7.38, 'tp': 8.43, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q3_W3_THU_NY_PM': {
        'LONG': {'sl': 4.29, 'tp': 5.14, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 4.29, 'tp': 5.14, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q3_W3_TUE_ASIA': {
        'LONG': {'sl': 1.69, 'tp': 1.93, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.69, 'tp': 1.93, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q3_W3_TUE_LONDON': {
        'LONG': {'sl': 1.83, 'tp': 3.66, 'sl_mult': 2.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 1.83, 'tp': 3.66, 'sl_mult': 2.5, 'tp_mult': 5.0},
    },
    'Q3_W3_TUE_NY_AM': {
        'LONG': {'sl': 6.62, 'tp': 9.46, 'sl_mult': 3.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 6.62, 'tp': 9.46, 'sl_mult': 3.5, 'tp_mult': 5.0},
    },
    'Q3_W3_TUE_NY_PM': {
        'LONG': {'sl': 3.84, 'tp': 4.61, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 3.84, 'tp': 4.61, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q3_W3_WED_ASIA': {
        'LONG': {'sl': 2.06, 'tp': 2.95, 'sl_mult': 3.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 2.06, 'tp': 2.95, 'sl_mult': 3.5, 'tp_mult': 5.0},
    },
    'Q3_W3_WED_LONDON': {
        'LONG': {'sl': 2.36, 'tp': 3.93, 'sl_mult': 3.0, 'tp_mult': 5.0},
        'SHORT': {'sl': 2.36, 'tp': 3.93, 'sl_mult': 3.0, 'tp_mult': 5.0},
    },
    'Q3_W3_WED_NY_AM': {
        'LONG': {'sl': 6.19, 'tp': 7.07, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 6.19, 'tp': 7.07, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q3_W3_WED_NY_PM': {
        'LONG': {'sl': 2.84, 'tp': 4.73, 'sl_mult': 1.5, 'tp_mult': 2.5},
        'SHORT': {'sl': 2.84, 'tp': 4.73, 'sl_mult': 1.5, 'tp_mult': 2.5},
    },
    'Q3_W4_FRI_ASIA': {
        'LONG': {'sl': 0.94, 'tp': 1.25, 'sl_mult': 1.5, 'tp_mult': 2.0},
        'SHORT': {'sl': 0.94, 'tp': 1.25, 'sl_mult': 1.5, 'tp_mult': 2.0},
    },
    'Q3_W4_FRI_LONDON': {
        'LONG': {'sl': 1.79, 'tp': 2.23, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 1.79, 'tp': 2.23, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q3_W4_FRI_NY_AM': {
        'LONG': {'sl': 4.54, 'tp': 5.67, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 4.54, 'tp': 5.67, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q3_W4_FRI_NY_PM': {
        'LONG': {'sl': 2.81, 'tp': 3.75, 'sl_mult': 1.5, 'tp_mult': 2.0},
        'SHORT': {'sl': 2.81, 'tp': 3.75, 'sl_mult': 1.5, 'tp_mult': 2.0},
    },
    'Q3_W4_MON_ASIA': {
        'LONG': {'sl': 1.55, 'tp': 2.59, 'sl_mult': 3.0, 'tp_mult': 5.0},
        'SHORT': {'sl': 1.55, 'tp': 2.59, 'sl_mult': 3.0, 'tp_mult': 5.0},
    },
    'Q3_W4_MON_LONDON': {
        'LONG': {'sl': 2.52, 'tp': 4.20, 'sl_mult': 3.0, 'tp_mult': 5.0},
        'SHORT': {'sl': 2.52, 'tp': 4.20, 'sl_mult': 3.0, 'tp_mult': 5.0},
    },
    'Q3_W4_MON_NY_AM': {
        'LONG': {'sl': 3.57, 'tp': 4.46, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 3.57, 'tp': 4.46, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q3_W4_MON_NY_PM': {
        'LONG': {'sl': 2.17, 'tp': 2.89, 'sl_mult': 1.5, 'tp_mult': 2.0},
        'SHORT': {'sl': 2.17, 'tp': 2.89, 'sl_mult': 1.5, 'tp_mult': 2.0},
    },
    'Q3_W4_THU_ASIA': {
        'LONG': {'sl': 0.88, 'tp': 1.47, 'sl_mult': 1.5, 'tp_mult': 2.5},
        'SHORT': {'sl': 0.88, 'tp': 1.47, 'sl_mult': 1.5, 'tp_mult': 2.5},
    },
    'Q3_W4_THU_LONDON': {
        'LONG': {'sl': 2.37, 'tp': 2.84, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 2.37, 'tp': 2.84, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q3_W4_THU_NY_AM': {
        'LONG': {'sl': 8.19, 'tp': 11.70, 'sl_mult': 3.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 8.19, 'tp': 11.70, 'sl_mult': 3.5, 'tp_mult': 5.0},
    },
    'Q3_W4_THU_NY_PM': {
        'LONG': {'sl': 4.00, 'tp': 6.00, 'sl_mult': 2.0, 'tp_mult': 3.0},
        'SHORT': {'sl': 4.00, 'tp': 6.00, 'sl_mult': 2.0, 'tp_mult': 3.0},
    },
    'Q3_W4_TUE_ASIA': {
        'LONG': {'sl': 1.61, 'tp': 2.14, 'sl_mult': 3.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.61, 'tp': 2.14, 'sl_mult': 3.0, 'tp_mult': 4.0},
    },
    'Q3_W4_TUE_LONDON': {
        'LONG': {'sl': 2.14, 'tp': 2.57, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 2.14, 'tp': 2.57, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q3_W4_TUE_NY_AM': {
        'LONG': {'sl': 4.51, 'tp': 5.41, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 4.51, 'tp': 5.41, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q3_W4_TUE_NY_PM': {
        'LONG': {'sl': 4.77, 'tp': 7.95, 'sl_mult': 3.0, 'tp_mult': 5.0},
        'SHORT': {'sl': 4.77, 'tp': 7.95, 'sl_mult': 3.0, 'tp_mult': 5.0},
    },
    'Q3_W4_WED_ASIA': {
        'LONG': {'sl': 1.14, 'tp': 1.71, 'sl_mult': 2.0, 'tp_mult': 3.0},
        'SHORT': {'sl': 1.14, 'tp': 1.71, 'sl_mult': 2.0, 'tp_mult': 3.0},
    },
    'Q3_W4_WED_LONDON': {
        'LONG': {'sl': 2.36, 'tp': 3.14, 'sl_mult': 3.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 2.36, 'tp': 3.14, 'sl_mult': 3.0, 'tp_mult': 4.0},
    },
    'Q3_W4_WED_NY_AM': {
        'LONG': {'sl': 6.12, 'tp': 7.00, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 6.12, 'tp': 7.00, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q3_W4_WED_NY_PM': {
        'LONG': {'sl': 4.51, 'tp': 5.41, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 4.51, 'tp': 5.41, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q4_W1_FRI_ASIA': {
        'LONG': {'sl': 1.75, 'tp': 2.00, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.75, 'tp': 2.00, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q4_W1_FRI_LONDON': {
        'LONG': {'sl': 2.05, 'tp': 2.46, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 2.05, 'tp': 2.46, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q4_W1_FRI_NY_AM': {
        'LONG': {'sl': 9.00, 'tp': 15.43, 'sl_mult': 3.5, 'tp_mult': 6.0},
        'SHORT': {'sl': 9.00, 'tp': 15.43, 'sl_mult': 3.5, 'tp_mult': 6.0},
    },
    'Q4_W1_FRI_NY_PM': {
        'LONG': {'sl': 3.54, 'tp': 4.42, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 3.54, 'tp': 4.42, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q4_W1_MON_ASIA': {
        'LONG': {'sl': 0.88, 'tp': 1.47, 'sl_mult': 1.5, 'tp_mult': 2.5},
        'SHORT': {'sl': 0.88, 'tp': 1.47, 'sl_mult': 1.5, 'tp_mult': 2.5},
    },
    'Q4_W1_MON_LONDON': {
        'LONG': {'sl': 3.38, 'tp': 3.86, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 3.38, 'tp': 3.86, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q4_W1_MON_NY_AM': {
        'LONG': {'sl': 3.61, 'tp': 4.51, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 3.61, 'tp': 4.51, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q4_W1_MON_NY_PM': {
        'LONG': {'sl': 5.12, 'tp': 5.86, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 5.12, 'tp': 5.86, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q4_W1_THU_ASIA': {
        'LONG': {'sl': 1.14, 'tp': 1.71, 'sl_mult': 2.0, 'tp_mult': 3.0},
        'SHORT': {'sl': 1.14, 'tp': 1.71, 'sl_mult': 2.0, 'tp_mult': 3.0},
    },
    'Q4_W1_THU_LONDON': {
        'LONG': {'sl': 3.31, 'tp': 5.68, 'sl_mult': 3.5, 'tp_mult': 6.0},
        'SHORT': {'sl': 3.31, 'tp': 5.68, 'sl_mult': 3.5, 'tp_mult': 6.0},
    },
    'Q4_W1_THU_NY_AM': {
        'LONG': {'sl': 6.69, 'tp': 11.46, 'sl_mult': 3.5, 'tp_mult': 6.0},
        'SHORT': {'sl': 6.69, 'tp': 11.46, 'sl_mult': 3.5, 'tp_mult': 6.0},
    },
    'Q4_W1_THU_NY_PM': {
        'LONG': {'sl': 3.14, 'tp': 3.93, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 3.14, 'tp': 3.93, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q4_W1_TUE_ASIA': {
        'LONG': {'sl': 2.19, 'tp': 2.50, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 2.19, 'tp': 2.50, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q4_W1_TUE_LONDON': {
        'LONG': {'sl': 2.32, 'tp': 3.71, 'sl_mult': 2.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 2.32, 'tp': 3.71, 'sl_mult': 2.5, 'tp_mult': 4.0},
    },
    'Q4_W1_TUE_NY_AM': {
        'LONG': {'sl': 7.25, 'tp': 8.29, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 7.25, 'tp': 8.29, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q4_W1_TUE_NY_PM': {
        'LONG': {'sl': 4.51, 'tp': 5.41, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 4.51, 'tp': 5.41, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q4_W1_WED_ASIA': {
        'LONG': {'sl': 1.32, 'tp': 1.98, 'sl_mult': 2.0, 'tp_mult': 3.0},
        'SHORT': {'sl': 1.32, 'tp': 1.98, 'sl_mult': 2.0, 'tp_mult': 3.0},
    },
    'Q4_W1_WED_LONDON': {
        'LONG': {'sl': 3.80, 'tp': 6.34, 'sl_mult': 3.0, 'tp_mult': 5.0},
        'SHORT': {'sl': 3.80, 'tp': 6.34, 'sl_mult': 3.0, 'tp_mult': 5.0},
    },
    'Q4_W1_WED_NY_AM': {
        'LONG': {'sl': 3.29, 'tp': 4.39, 'sl_mult': 1.5, 'tp_mult': 2.0},
        'SHORT': {'sl': 3.29, 'tp': 4.39, 'sl_mult': 1.5, 'tp_mult': 2.0},
    },
    'Q4_W1_WED_NY_PM': {
        'LONG': {'sl': 3.11, 'tp': 3.88, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 3.11, 'tp': 3.88, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q4_W2_FRI_ASIA': {
        'LONG': {'sl': 1.56, 'tp': 2.68, 'sl_mult': 3.5, 'tp_mult': 6.0},
        'SHORT': {'sl': 1.56, 'tp': 2.68, 'sl_mult': 3.5, 'tp_mult': 6.0},
    },
    'Q4_W2_FRI_LONDON': {
        'LONG': {'sl': 2.68, 'tp': 4.46, 'sl_mult': 3.0, 'tp_mult': 5.0},
        'SHORT': {'sl': 2.68, 'tp': 4.46, 'sl_mult': 3.0, 'tp_mult': 5.0},
    },
    'Q4_W2_FRI_NY_AM': {
        'LONG': {'sl': 5.36, 'tp': 10.71, 'sl_mult': 2.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 5.36, 'tp': 10.71, 'sl_mult': 2.5, 'tp_mult': 5.0},
    },
    'Q4_W2_FRI_NY_PM': {
        'LONG': {'sl': 4.45, 'tp': 5.93, 'sl_mult': 3.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 4.45, 'tp': 5.93, 'sl_mult': 3.0, 'tp_mult': 4.0},
    },
    'Q4_W2_MON_ASIA': {
        'LONG': {'sl': 1.62, 'tp': 1.86, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.62, 'tp': 1.86, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q4_W2_MON_LONDON': {
        'LONG': {'sl': 1.88, 'tp': 3.00, 'sl_mult': 2.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.88, 'tp': 3.00, 'sl_mult': 2.5, 'tp_mult': 4.0},
    },
    'Q4_W2_MON_NY_AM': {
        'LONG': {'sl': 6.12, 'tp': 10.50, 'sl_mult': 3.5, 'tp_mult': 6.0},
        'SHORT': {'sl': 6.12, 'tp': 10.50, 'sl_mult': 3.5, 'tp_mult': 6.0},
    },
    'Q4_W2_MON_NY_PM': {
        'LONG': {'sl': 3.30, 'tp': 3.96, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 3.30, 'tp': 3.96, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q4_W2_THU_ASIA': {
        'LONG': {'sl': 1.75, 'tp': 2.00, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.75, 'tp': 2.00, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q4_W2_THU_LONDON': {
        'LONG': {'sl': 1.54, 'tp': 1.92, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 1.54, 'tp': 1.92, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q4_W2_THU_NY_AM': {
        'LONG': {'sl': 7.44, 'tp': 8.50, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 7.44, 'tp': 8.50, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q4_W2_THU_NY_PM': {
        'LONG': {'sl': 3.54, 'tp': 4.42, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 3.54, 'tp': 4.42, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q4_W2_TUE_ASIA': {
        'LONG': {'sl': 1.21, 'tp': 1.45, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 1.21, 'tp': 1.45, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q4_W2_TUE_LONDON': {
        'LONG': {'sl': 2.79, 'tp': 3.71, 'sl_mult': 3.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 2.79, 'tp': 3.71, 'sl_mult': 3.0, 'tp_mult': 4.0},
    },
    'Q4_W2_TUE_NY_AM': {
        'LONG': {'sl': 6.62, 'tp': 11.36, 'sl_mult': 3.5, 'tp_mult': 6.0},
        'SHORT': {'sl': 6.62, 'tp': 11.36, 'sl_mult': 3.5, 'tp_mult': 6.0},
    },
    'Q4_W2_TUE_NY_PM': {
        'LONG': {'sl': 4.29, 'tp': 8.57, 'sl_mult': 3.0, 'tp_mult': 6.0},
        'SHORT': {'sl': 4.29, 'tp': 8.57, 'sl_mult': 3.0, 'tp_mult': 6.0},
    },
    'Q4_W2_WED_ASIA': {
        'LONG': {'sl': 1.45, 'tp': 1.93, 'sl_mult': 3.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.45, 'tp': 1.93, 'sl_mult': 3.0, 'tp_mult': 4.0},
    },
    'Q4_W2_WED_LONDON': {
        'LONG': {'sl': 1.79, 'tp': 2.14, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 1.79, 'tp': 2.14, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q4_W2_WED_NY_AM': {
        'LONG': {'sl': 2.54, 'tp': 4.24, 'sl_mult': 1.5, 'tp_mult': 2.5},
        'SHORT': {'sl': 2.54, 'tp': 4.24, 'sl_mult': 1.5, 'tp_mult': 2.5},
    },
    'Q4_W2_WED_NY_PM': {
        'LONG': {'sl': 4.81, 'tp': 5.50, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 4.81, 'tp': 5.50, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q4_W3_FRI_ASIA': {
        'LONG': {'sl': 2.06, 'tp': 3.54, 'sl_mult': 3.5, 'tp_mult': 6.0},
        'SHORT': {'sl': 2.06, 'tp': 3.54, 'sl_mult': 3.5, 'tp_mult': 6.0},
    },
    'Q4_W3_FRI_LONDON': {
        'LONG': {'sl': 2.41, 'tp': 2.89, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 2.41, 'tp': 2.89, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q4_W3_FRI_NY_AM': {
        'LONG': {'sl': 6.16, 'tp': 7.39, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 6.16, 'tp': 7.39, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q4_W3_FRI_NY_PM': {
        'LONG': {'sl': 2.97, 'tp': 3.96, 'sl_mult': 1.5, 'tp_mult': 2.0},
        'SHORT': {'sl': 2.97, 'tp': 3.96, 'sl_mult': 1.5, 'tp_mult': 2.0},
    },
    'Q4_W3_MON_ASIA': {
        'LONG': {'sl': 1.39, 'tp': 2.79, 'sl_mult': 3.0, 'tp_mult': 6.0},
        'SHORT': {'sl': 1.39, 'tp': 2.79, 'sl_mult': 3.0, 'tp_mult': 6.0},
    },
    'Q4_W3_MON_LONDON': {
        'LONG': {'sl': 3.12, 'tp': 4.46, 'sl_mult': 3.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 3.12, 'tp': 4.46, 'sl_mult': 3.5, 'tp_mult': 5.0},
    },
    'Q4_W3_MON_NY_AM': {
        'LONG': {'sl': 4.77, 'tp': 7.95, 'sl_mult': 3.0, 'tp_mult': 5.0},
        'SHORT': {'sl': 4.77, 'tp': 7.95, 'sl_mult': 3.0, 'tp_mult': 5.0},
    },
    'Q4_W3_MON_NY_PM': {
        'LONG': {'sl': 3.59, 'tp': 5.98, 'sl_mult': 3.0, 'tp_mult': 5.0},
        'SHORT': {'sl': 3.59, 'tp': 5.98, 'sl_mult': 3.0, 'tp_mult': 5.0},
    },
    'Q4_W3_THU_ASIA': {
        'LONG': {'sl': 1.10, 'tp': 1.46, 'sl_mult': 1.5, 'tp_mult': 2.0},
        'SHORT': {'sl': 1.10, 'tp': 1.46, 'sl_mult': 1.5, 'tp_mult': 2.0},
    },
    'Q4_W3_THU_LONDON': {
        'LONG': {'sl': 1.69, 'tp': 2.25, 'sl_mult': 1.5, 'tp_mult': 2.0},
        'SHORT': {'sl': 1.69, 'tp': 2.25, 'sl_mult': 1.5, 'tp_mult': 2.0},
    },
    'Q4_W3_THU_NY_AM': {
        'LONG': {'sl': 8.94, 'tp': 10.21, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 8.94, 'tp': 10.21, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q4_W3_THU_NY_PM': {
        'LONG': {'sl': 4.29, 'tp': 5.36, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 4.29, 'tp': 5.36, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q4_W3_TUE_ASIA': {
        'LONG': {'sl': 1.25, 'tp': 2.00, 'sl_mult': 2.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.25, 'tp': 2.00, 'sl_mult': 2.5, 'tp_mult': 4.0},
    },
    'Q4_W3_TUE_LONDON': {
        'LONG': {'sl': 1.29, 'tp': 1.71, 'sl_mult': 1.5, 'tp_mult': 2.0},
        'SHORT': {'sl': 1.29, 'tp': 1.71, 'sl_mult': 1.5, 'tp_mult': 2.0},
    },
    'Q4_W3_TUE_NY_AM': {
        'LONG': {'sl': 4.69, 'tp': 5.62, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 4.69, 'tp': 5.62, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q4_W3_TUE_NY_PM': {
        'LONG': {'sl': 3.53, 'tp': 4.23, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 3.53, 'tp': 4.23, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q4_W3_WED_ASIA': {
        'LONG': {'sl': 1.04, 'tp': 1.74, 'sl_mult': 1.5, 'tp_mult': 2.5},
        'SHORT': {'sl': 1.04, 'tp': 1.74, 'sl_mult': 1.5, 'tp_mult': 2.5},
    },
    'Q4_W3_WED_LONDON': {
        'LONG': {'sl': 3.31, 'tp': 4.73, 'sl_mult': 3.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 3.31, 'tp': 4.73, 'sl_mult': 3.5, 'tp_mult': 5.0},
    },
    'Q4_W3_WED_NY_AM': {
        'LONG': {'sl': 6.19, 'tp': 7.07, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 6.19, 'tp': 7.07, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q4_W3_WED_NY_PM': {
        'LONG': {'sl': 3.82, 'tp': 7.64, 'sl_mult': 2.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 3.82, 'tp': 7.64, 'sl_mult': 2.0, 'tp_mult': 4.0},
    },
    'Q4_W4_FRI_ASIA': {
        'LONG': {'sl': 1.81, 'tp': 3.11, 'sl_mult': 3.5, 'tp_mult': 6.0},
        'SHORT': {'sl': 1.81, 'tp': 3.11, 'sl_mult': 3.5, 'tp_mult': 6.0},
    },
    'Q4_W4_FRI_LONDON': {
        'LONG': {'sl': 1.54, 'tp': 1.92, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 1.54, 'tp': 1.92, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q4_W4_FRI_NY_AM': {
        'LONG': {'sl': 6.38, 'tp': 10.93, 'sl_mult': 3.5, 'tp_mult': 6.0},
        'SHORT': {'sl': 6.38, 'tp': 10.93, 'sl_mult': 3.5, 'tp_mult': 6.0},
    },
    'Q4_W4_FRI_NY_PM': {
        'LONG': {'sl': 4.55, 'tp': 9.11, 'sl_mult': 2.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 4.55, 'tp': 9.11, 'sl_mult': 2.5, 'tp_mult': 5.0},
    },
    'Q4_W4_MON_ASIA': {
        'LONG': {'sl': 1.77, 'tp': 2.36, 'sl_mult': 3.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.77, 'tp': 2.36, 'sl_mult': 3.0, 'tp_mult': 4.0},
    },
    'Q4_W4_MON_LONDON': {
        'LONG': {'sl': 2.79, 'tp': 3.71, 'sl_mult': 3.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 2.79, 'tp': 3.71, 'sl_mult': 3.0, 'tp_mult': 4.0},
    },
    'Q4_W4_MON_NY_AM': {
        'LONG': {'sl': 7.69, 'tp': 8.79, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 7.69, 'tp': 8.79, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q4_W4_MON_NY_PM': {
        'LONG': {'sl': 2.62, 'tp': 3.50, 'sl_mult': 1.5, 'tp_mult': 2.0},
        'SHORT': {'sl': 2.62, 'tp': 3.50, 'sl_mult': 1.5, 'tp_mult': 2.0},
    },
    'Q4_W4_THU_ASIA': {
        'LONG': {'sl': 0.78, 'tp': 1.29, 'sl_mult': 1.5, 'tp_mult': 2.5},
        'SHORT': {'sl': 0.78, 'tp': 1.29, 'sl_mult': 1.5, 'tp_mult': 2.5},
    },
    'Q4_W4_THU_LONDON': {
        'LONG': {'sl': 2.28, 'tp': 2.73, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 2.28, 'tp': 2.73, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q4_W4_THU_NY_AM': {
        'LONG': {'sl': 6.81, 'tp': 7.79, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 6.81, 'tp': 7.79, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q4_W4_THU_NY_PM': {
        'LONG': {'sl': 4.51, 'tp': 5.41, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 4.51, 'tp': 5.41, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q4_W4_TUE_ASIA': {
        'LONG': {'sl': 1.11, 'tp': 2.21, 'sl_mult': 2.0, 'tp_mult': 4.0},
        'SHORT': {'sl': 1.11, 'tp': 2.21, 'sl_mult': 2.0, 'tp_mult': 4.0},
    },
    'Q4_W4_TUE_LONDON': {
        'LONG': {'sl': 1.93, 'tp': 2.41, 'sl_mult': 2.0, 'tp_mult': 2.5},
        'SHORT': {'sl': 1.93, 'tp': 2.41, 'sl_mult': 2.0, 'tp_mult': 2.5},
    },
    'Q4_W4_TUE_NY_AM': {
        'LONG': {'sl': 6.31, 'tp': 7.21, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 6.31, 'tp': 7.21, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q4_W4_TUE_NY_PM': {
        'LONG': {'sl': 5.31, 'tp': 6.07, 'sl_mult': 3.5, 'tp_mult': 4.0},
        'SHORT': {'sl': 5.31, 'tp': 6.07, 'sl_mult': 3.5, 'tp_mult': 4.0},
    },
    'Q4_W4_WED_ASIA': {
        'LONG': {'sl': 1.04, 'tp': 1.55, 'sl_mult': 2.0, 'tp_mult': 3.0},
        'SHORT': {'sl': 1.04, 'tp': 1.55, 'sl_mult': 2.0, 'tp_mult': 3.0},
    },
    'Q4_W4_WED_LONDON': {
        'LONG': {'sl': 2.05, 'tp': 2.46, 'sl_mult': 2.5, 'tp_mult': 3.0},
        'SHORT': {'sl': 2.05, 'tp': 2.46, 'sl_mult': 2.5, 'tp_mult': 3.0},
    },
    'Q4_W4_WED_NY_AM': {
        'LONG': {'sl': 3.61, 'tp': 5.41, 'sl_mult': 2.0, 'tp_mult': 3.0},
        'SHORT': {'sl': 3.61, 'tp': 5.41, 'sl_mult': 2.0, 'tp_mult': 3.0},
    },
    'Q4_W4_WED_NY_PM': {
        'LONG': {'sl': 5.88, 'tp': 8.39, 'sl_mult': 3.5, 'tp_mult': 5.0},
        'SHORT': {'sl': 5.88, 'tp': 8.39, 'sl_mult': 3.5, 'tp_mult': 5.0},
    },
}

def get_regime_sltp(direction, yq, mq, dow, sess):
    """Get SL/TP parameters for a specific regime combo."""
    combo_key = f"{yq}_{mq}_{dow}_{sess}"
    if combo_key not in PARAMS:
        return {'sl': 2.0, 'tp': 3.0, 'sl_mult': 2.0, 'tp_mult': 3.0}
    return PARAMS[combo_key][direction]

def is_reverted_combo(yq, mq, dow, sess):
    """Check if a combo uses reverted signals."""
    combo_key = f"{yq}_{mq}_{dow}_{sess}"
    return combo_key in REVERTED_COMBOS

def get_quality_tier(yq, mq, dow, sess):
    """
    Get quality tier for a combo.
    Returns: 1 (high), 2 (medium), 3 (low), 4 (default), or None
    """
    combo_key = f"{yq}_{mq}_{dow}_{sess}"
    return QUALITY_TIERS.get(combo_key)