#!/usr/bin/env python3
"""Analyze the current-bot replay log for Kalshi-only-blocker behavior.

Reads backtest_reports/kalshi_only_currentbot_2025_09/topstep_live_bot.log
(generated by tools/run_full_live_replay_parquet.py with all non-Kalshi
blockers env-disabled). Reports:

  - signal pipeline funnel (signal → filter → same-side ML → Kalshi → exec)
  - Kalshi PASS / BLOCK distribution + decision quality
  - actual closed-trade PnL vs counterfactual
  - comparison to old (hard-rule) Sep replay
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from collections import Counter

NEW_LOG = Path("backtest_reports/kalshi_only_currentbot_2025_09/topstep_live_bot.log")
NEW_TRADES = Path("backtest_reports/kalshi_only_currentbot_2025_09/closed_trades.json")
OLD_LOG = Path("backtest_reports/full_live_replay/2025_09/topstep_live_bot.log")
OLD_TRADES = Path("backtest_reports/full_live_replay/2025_09/closed_trades.json")


RE_BAR = re.compile(r"Bar: 2025-09-\d{2} (\d{2}):")
RE_SIG = re.compile(r"\[STRATEGY_SIGNAL\] 📊 ([A-Za-z]+(?:Strategy)?).*generated (LONG|SHORT) signal")
RE_KALSHI_VIEW = re.compile(r"\[KALSHI_ENTRY_VIEW\].*decision=(PASS|BLOCK)")
RE_SAMESIDE_IGNORED = re.compile(r"Ignoring same-side signal")
RE_TRADE_PLACED = re.compile(r"\[TRADE_PLACED\]")
RE_FAST_EXEC = re.compile(r"FAST EXEC:")
RE_FILTER_BLOCK = re.compile(r"\[FILTER_CHECK\] ✗ BLOCK")


def analyze(log_path: Path, label: str) -> dict:
    if not log_path.exists():
        return {"label": label, "missing": True}

    counts = Counter()
    last_bar_hour = None
    settle_signals = 0
    by_hour_signals = Counter()
    by_hour_kalshi = Counter()
    kalshi_decisions = []     # list of "PASS" or "BLOCK"
    same_side_ignored_settle = 0
    fast_exec_settle = 0
    trade_placed_settle = 0

    with log_path.open(errors="ignore") as f:
        for line in f:
            bm = RE_BAR.search(line)
            if bm:
                last_bar_hour = int(bm.group(1))
                continue
            if RE_SIG.search(line):
                counts["strategy_signal"] += 1
                if last_bar_hour is not None and 12 <= last_bar_hour <= 16:
                    settle_signals += 1
                    by_hour_signals[last_bar_hour] += 1
                continue
            kv = RE_KALSHI_VIEW.search(line)
            if kv:
                counts["kalshi_entry_view"] += 1
                kalshi_decisions.append(kv.group(1))
                if last_bar_hour is not None:
                    by_hour_kalshi[last_bar_hour] += 1
                continue
            if RE_SAMESIDE_IGNORED.search(line):
                counts["same_side_ignored"] += 1
                if last_bar_hour is not None and 12 <= last_bar_hour <= 16:
                    same_side_ignored_settle += 1
                continue
            if RE_TRADE_PLACED.search(line):
                counts["trade_placed"] += 1
                if last_bar_hour is not None and 12 <= last_bar_hour <= 16:
                    trade_placed_settle += 1
                continue
            if RE_FAST_EXEC.search(line):
                counts["fast_exec"] += 1
                if last_bar_hour is not None and 12 <= last_bar_hour <= 16:
                    fast_exec_settle += 1
                continue
            if RE_FILTER_BLOCK.search(line):
                counts["filter_check_blocked"] += 1
                continue

    # Kalshi decision distribution
    kalshi_pass = sum(1 for d in kalshi_decisions if d == "PASS")
    kalshi_block = sum(1 for d in kalshi_decisions if d == "BLOCK")

    return {
        "label": label,
        "log_path": str(log_path),
        "counts": dict(counts),
        "settle_signals": settle_signals,
        "settle_same_side_blocked": same_side_ignored_settle,
        "settle_fast_exec": fast_exec_settle,
        "settle_trade_placed": trade_placed_settle,
        "by_hour_signals": dict(by_hour_signals),
        "by_hour_kalshi_views": dict(by_hour_kalshi),
        "kalshi_pass": kalshi_pass,
        "kalshi_block": kalshi_block,
        "kalshi_pass_rate": kalshi_pass / max(1, kalshi_pass + kalshi_block),
        "kalshi_view_per_signal": counts.get("kalshi_entry_view", 0) / max(1, counts.get("strategy_signal", 0)),
    }


def trade_summary(trades_path: Path) -> dict:
    if not trades_path.exists() or trades_path.stat().st_size < 5:
        return {"trades": 0}
    try:
        trades = json.loads(trades_path.read_text())
    except Exception as e:
        return {"error": str(e)}
    if not trades:
        return {"trades": 0}
    n = len(trades)
    pnl = sum(float(t.get("pnl_dollars", 0) or 0) for t in trades)
    wins = sum(1 for t in trades if float(t.get("pnl_dollars", 0) or 0) > 0)
    losses = sum(1 for t in trades if float(t.get("pnl_dollars", 0) or 0) < 0)
    by_strategy = Counter(t.get("strategy", "?") for t in trades)
    by_side = Counter(t.get("side", "?") for t in trades)
    cum_pnl = []
    running = 0.0
    for t in sorted(trades, key=lambda x: x.get("entry_time", "")):
        running += float(t.get("pnl_dollars", 0) or 0)
        cum_pnl.append(running)
    peak = 0.0
    max_dd = 0.0
    for v in cum_pnl:
        peak = max(peak, v)
        max_dd = max(max_dd, peak - v)
    return {
        "trades": n,
        "pnl": pnl,
        "wins": wins, "losses": losses,
        "wr_pct": 100*wins/max(1, n),
        "avg_pnl": pnl/max(1, n),
        "max_dd": max_dd,
        "by_strategy": dict(by_strategy),
        "by_side": dict(by_side),
    }


def main():
    print("="*78)
    print("CURRENT-BOT REPLAY ANALYSIS — 2025-09-01 to 2025-09-14")
    print("="*78)

    new = analyze(NEW_LOG, "current bot (Kalshi-only blocker)")
    old = analyze(OLD_LOG, "old bot (hard-rule same-side)")

    if new.get("missing"):
        print(f"  NEW log not found yet: {NEW_LOG}")
        return 1

    print(f"\n{'metric':<35} {'OLD (hard-rule)':>20} {'NEW (SameSide ML, others off)':>35}")
    print("─"*92)
    metrics = [
        ("strategy_signals total", new["counts"].get("strategy_signal", 0), old["counts"].get("strategy_signal", 0)),
        ("settle-hour signals (12-16 ET)", new["settle_signals"], old["settle_signals"]),
        ("same-side ignored (settle)", new["settle_same_side_blocked"], old["settle_same_side_blocked"]),
        ("FAST EXEC (settle)", new["settle_fast_exec"], old["settle_fast_exec"]),
        ("TRADE_PLACED (settle)", new["settle_trade_placed"], old["settle_trade_placed"]),
        ("KALSHI_ENTRY_VIEW total", new["counts"].get("kalshi_entry_view", 0), old["counts"].get("kalshi_entry_view", 0)),
        ("Kalshi views / strategy_signal", f"{100*new['kalshi_view_per_signal']:.1f}%", f"{100*old['kalshi_view_per_signal']:.1f}%"),
        ("Kalshi PASS / BLOCK", f"{new['kalshi_pass']} / {new['kalshi_block']}", f"{old['kalshi_pass']} / {old['kalshi_block']}"),
        ("Kalshi pass-rate", f"{100*new['kalshi_pass_rate']:.1f}%", f"{100*old['kalshi_pass_rate']:.1f}%"),
    ]
    for m, n, o in metrics:
        print(f"  {m:<35} {str(o):>20} {str(n):>35}")

    print(f"\n{'='*78}")
    print("CLOSED-TRADE PNL COMPARISON")
    print(f"{'='*78}")
    new_t = trade_summary(NEW_TRADES)
    old_t = trade_summary(OLD_TRADES)
    print(f"\n{'metric':<25} {'OLD':>20} {'NEW':>20}")
    print("─"*70)
    keys = [("trades", "n"), ("pnl", "$"), ("wr_pct", "%"), ("avg_pnl", "$"), ("max_dd", "$")]
    for k, suffix in keys:
        ov = old_t.get(k, "n/a"); nv = new_t.get(k, "n/a")
        if isinstance(ov, float):
            ov_s = f"${ov:+,.2f}" if suffix == "$" else f"{ov:.1f}{suffix}"
        else:
            ov_s = str(ov)
        if isinstance(nv, float):
            nv_s = f"${nv:+,.2f}" if suffix == "$" else f"{nv:.1f}{suffix}"
        else:
            nv_s = str(nv)
        print(f"  {k:<25} {ov_s:>20} {nv_s:>20}")

    print("\nNew bot — by strategy:")
    for s, n in sorted(new_t.get("by_strategy", {}).items(), key=lambda x: -x[1]):
        print(f"  {s:<30} {n}")

    if new["counts"].get("kalshi_entry_view", 0) > 0:
        print(f"\n  Kalshi gate behavior (current bot):")
        print(f"    PASSes: {new['kalshi_pass']}  → would let trade through")
        print(f"    BLOCKs: {new['kalshi_block']} → would veto")
        print(f"    pass-rate: {100*new['kalshi_pass_rate']:.1f}%")

    return 0


if __name__ == "__main__":
    sys.exit(main())
