#!/usr/bin/env python3
"""Phase 3a — Kalshi Gate Reconstruction v2 (corrected simulator).

This recomputes Section 8.19 of the strategy journal using the FIXED
trade-through simulator (`simulator_trade_through.py`) AND the corrected
gate semantics. It also corrects an inversion error found in the OLD
parquet (`artifacts/kalshi_gate_reconstruction_14mo.parquet`) where the
gate label was the opposite of what the live code expects.

Inputs
------
- artifacts/full_overlay_stack_simulation_14mo.parquet
    Candidate stream with the model's k_proba already computed
    (3,438 candidates over 14 months, Mar 2025 - Apr 2026).
    Note: the parquet's `k_decision` is the LIVE-CORRECT label
    (PASS when proba >= pass_threshold (0.5); BLOCK otherwise),
    matching `train_kalshi_ml.py`'s label = 1 if pnl > 0 (it
    predicts P(winner)).
- artifacts/filterless_reconstruction_14mo_v2.parquet
    Already walked-forward with the FIXED simulator. Each row's
    `net_pnl_after_haircut` is the corrected outcome under the
    conservative trade-through TP rule.
- artifacts/kalshi_gate_reconstruction_14mo.parquet
    Old reconstruction (broken sim + inverted labels). Used only for
    bringing forward the gate_active flag (the 12-16 ET window) for
    rows we cannot derive otherwise. We OVERRIDE `gate_decision` with
    the candidate-stream's correct semantics.

Process
-------
1. Build a unified per-candidate frame with:
     - corrected forward outcome (from v2 baseline)
     - the gate's k_proba and live-correct k_decision (from candidate
       stream)
     - gate_active flag = (12 <= et_hour <= 16)
2. Compute counterfactual:
     - "no_gate"  : take every candidate; apply single-position
                    friend rule
     - "with_gate": skip every candidate where gate_active=1 and
                    k_decision=BLOCK; apply single-position friend
                    rule on the remaining stream
   The friend rule is recomputed AFTER blocking, so blocked
   candidates free up the queue for downstream candidates.
3. Per-month and aggregate roll-up: trades / WR% / PnL / DD.
4. Write `artifacts/kalshi_gate_reconstruction_14mo_v2.parquet` and
   `artifacts/kalshi_v2_summary.json`.

Output: `/tmp/phase3a_kalshi_v2_report.md` is generated by the caller.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
SIGS_PATH = ROOT / "artifacts" / "full_overlay_stack_simulation_14mo.parquet"
V2_PATH = ROOT / "artifacts" / "filterless_reconstruction_14mo_v2.parquet"
OLD_RECON_PATH = ROOT / "artifacts" / "kalshi_gate_reconstruction_14mo.parquet"

OUT_PARQUET = ROOT / "artifacts" / "kalshi_gate_reconstruction_14mo_v2.parquet"
OUT_SUMMARY = ROOT / "artifacts" / "kalshi_v2_summary.json"

HORIZON = 30  # bars
KALSHI_HOURS_ET = {12, 13, 14, 15, 16}


def _ts_naive(s: pd.Series) -> pd.Series:
    """Coerce timestamp series to tz-naive ET wall-clock."""
    out = pd.to_datetime(s.astype(str).str[:19])
    return out


def main() -> int:
    print("[recon-v2] loading candidate stream:", SIGS_PATH)
    sigs = pd.read_parquet(SIGS_PATH)
    sigs = sigs.copy()
    sigs["ts_n"] = _ts_naive(sigs["ts"])
    sigs = sigs.sort_values("ts_n").reset_index(drop=True)
    print(f"  candidates: n={len(sigs)}")

    print("[recon-v2] loading v2 baseline (fixed sim):", V2_PATH)
    v2 = pd.read_parquet(V2_PATH).copy()
    v2["ts_n"] = _ts_naive(v2["ts"])
    print(f"  v2 rows: {len(v2)}")

    # Sanity: row counts should match.
    if len(sigs) != len(v2):
        print(f"[recon-v2][warn] sigs and v2 differ in row count: {len(sigs)} vs {len(v2)}")

    # Join v2 corrected outcome onto candidate stream by (ts_n, strategy, side).
    keys = ["ts_n", "strategy", "side"]
    v2_sub = v2[keys + [
        "exit_reason", "exit_price", "exit_bar", "exit_ts",
        "raw_pnl", "net_pnl_after_haircut", "contract", "horizon_bars",
    ]]
    df = sigs.merge(v2_sub, on=keys, how="left", suffixes=("", "_v2"))
    miss = df["exit_reason"].isna().sum()
    print(f"[recon-v2] candidates without a v2 walk-forward row: {miss}")
    if miss:
        # Fill with no-data so the friend-rule simulator can advance.
        df.loc[df["exit_reason"].isna(), "exit_reason"] = "no_data"
        df.loc[df["raw_pnl"].isna(), "raw_pnl"] = 0.0
        df.loc[df["net_pnl_after_haircut"].isna(), "net_pnl_after_haircut"] = 0.0

    # Gate active flag = 12 <= ET_hour <= 16
    et_hour = df["ts_n"].dt.hour
    df["gate_active"] = et_hour.isin(KALSHI_HOURS_ET).astype(int)

    # Use the candidate-stream's k_decision (live-correct semantics):
    # PASS when proba >= 0.5 (predicted winner); BLOCK when proba < 0.5.
    df["k_decision_corrected"] = df["k_decision"].fillna("NA").astype(str)
    df["k_proba_used"] = df["k_proba"]

    # When gate_active=1 but k_decision is "NA" (no proba in stream),
    # fall back to PASS (no block) — same convention as the live rule
    # when no Kalshi data is available.
    df.loc[(df["gate_active"] == 1) & (df["k_decision_corrected"] == "NA"),
           "k_decision_corrected"] = "PASS"
    # When gate_active=0, force NA.
    df.loc[df["gate_active"] == 0, "k_decision_corrected"] = "NA"

    # ---- Friend-rule walk: build "no gate" and "with gate" trade lists ----
    def walk_friend_rule(rows: pd.DataFrame, blocked_mask: np.ndarray) -> pd.DataFrame:
        """Walk rows in time order; skip if a prior trade is still open
        OR the candidate is blocked. blocked_mask is per-row True=block."""
        out = rows.copy().reset_index(drop=True)
        out["taken"] = False
        out["blocked_by_gate"] = False
        next_open_at = None
        n = len(out)
        for i in range(n):
            ts = out.at[i, "ts_n"]
            if blocked_mask[i]:
                out.at[i, "blocked_by_gate"] = True
                # Blocked candidates do NOT consume the friend-rule slot
                # (no trade enters the market).
                continue
            if next_open_at is not None and ts < next_open_at:
                continue
            # Take the trade.
            out.at[i, "taken"] = True
            exit_ts = out.at[i, "exit_ts"]
            if pd.notna(exit_ts):
                next_open_at = pd.Timestamp(exit_ts)
                # Strip tz to compare with ts_n (naive)
                if next_open_at.tzinfo is not None:
                    next_open_at = next_open_at.tz_convert("US/Eastern").tz_localize(None)
            else:
                next_open_at = ts + pd.Timedelta(minutes=HORIZON)
        return out

    print("[recon-v2] walking 'no gate' (filterless control)")
    no_block = np.zeros(len(df), dtype=bool)
    no_gate = walk_friend_rule(df, no_block)

    print("[recon-v2] walking 'with Kalshi gate' (corrected semantics)")
    blocked_with_gate = (df["k_decision_corrected"] == "BLOCK").to_numpy()
    with_gate = walk_friend_rule(df, blocked_with_gate)

    # ---- Per-month aggregator ----
    def aggregate(walk_df: pd.DataFrame) -> pd.DataFrame:
        taken = walk_df[walk_df["taken"]].copy()
        if taken.empty:
            return pd.DataFrame(columns=["month", "trades", "wr", "pnl", "dd"])
        taken["month"] = taken["ts_n"].dt.strftime("%Y-%m")
        out = []
        for month, sub in taken.groupby("month", sort=True):
            n = len(sub)
            wins = int((sub["raw_pnl"] > 0).sum())
            wr = 100.0 * wins / n if n else 0.0
            pnl = float(sub["net_pnl_after_haircut"].sum())
            cum = sub.sort_values("ts_n")["net_pnl_after_haircut"].cumsum()
            dd = float((cum - cum.cummax()).min()) if len(cum) else 0.0
            out.append({"month": month, "trades": n, "wr": round(wr, 2),
                        "pnl": round(pnl, 2), "dd": round(dd, 2)})
        return pd.DataFrame(out)

    no_gate_pm = aggregate(no_gate)
    with_gate_pm = aggregate(with_gate)

    def rollup(walk_df: pd.DataFrame) -> dict:
        taken = walk_df[walk_df["taken"]].copy()
        n = len(taken)
        wins = int((taken["raw_pnl"] > 0).sum())
        wr = 100.0 * wins / n if n else 0.0
        pnl_raw = float(taken["raw_pnl"].sum())
        pnl_net = float(taken["net_pnl_after_haircut"].sum())
        cum = taken.sort_values("ts_n")["net_pnl_after_haircut"].cumsum()
        dd = float((cum - cum.cummax()).min()) if len(cum) else 0.0
        return {
            "trades": int(n),
            "wr": round(wr, 2),
            "pnl_raw": round(pnl_raw, 2),
            "pnl_net": round(pnl_net, 2),
            "max_dd": round(dd, 2),
        }

    no_gate_agg = rollup(no_gate)
    with_gate_agg = rollup(with_gate)

    delta = {
        "trades_delta": with_gate_agg["trades"] - no_gate_agg["trades"],
        "pnl_net_delta": round(with_gate_agg["pnl_net"] - no_gate_agg["pnl_net"], 2),
        "dd_delta": round(with_gate_agg["max_dd"] - no_gate_agg["max_dd"], 2),
        "blocked_count": int(blocked_with_gate.sum()),
        "blocked_winners": int(((df["raw_pnl"] > 0) & blocked_with_gate).sum()),
        "blocked_losers": int(((df["raw_pnl"] < 0) & blocked_with_gate).sum()),
    }

    # Build verdict
    if delta["pnl_net_delta"] > 250:
        verdict = "HELPS"
    elif delta["pnl_net_delta"] < -250:
        verdict = "HURTS"
    else:
        verdict = "WASH"

    # ---- Write outputs ----
    # Reconstruction parquet: per-candidate richer schema
    out_df = df[[
        "ts_n", "month", "strategy", "family", "side", "price", "sl", "tp",
        "k_proba_used", "k_decision_corrected", "gate_active",
        "exit_reason", "exit_price", "exit_bar", "exit_ts",
        "raw_pnl", "net_pnl_after_haircut", "contract",
    ]].copy()
    out_df["taken_no_gate"] = no_gate["taken"].values
    out_df["taken_with_gate"] = with_gate["taken"].values
    out_df["blocked_by_kalshi"] = with_gate["blocked_by_gate"].values
    out_df.to_parquet(OUT_PARQUET, index=False)
    print(f"[recon-v2] wrote {OUT_PARQUET} ({len(out_df)} rows)")

    # Summary JSON
    summary = {
        "method": "Phase 3a corrected: fixed simulator + corrected gate semantics + friend-rule walk on each policy",
        "candidates_total": int(len(df)),
        "gate_active_count": int(df["gate_active"].sum()),
        "kalshi_block_count": int(blocked_with_gate.sum()),
        "kalshi_pass_count": int((df["k_decision_corrected"] == "PASS").sum()),
        "no_gate": no_gate_agg,
        "with_gate": with_gate_agg,
        "delta_with_minus_no": delta,
        "verdict": verdict,
        "per_month_no_gate": no_gate_pm.to_dict(orient="records"),
        "per_month_with_gate": with_gate_pm.to_dict(orient="records"),
        "notes": [
            "Gate semantics: pass_threshold=0.5; PASS when k_proba >= 0.5 (predicted winner). This is the LIVE-correct semantics — opposite of what artifacts/kalshi_gate_reconstruction_14mo.parquet stored.",
            "Section 8.19's headline (-$70,854 if wired) was computed with INVERTED labels.",
            "Friend rule is rewalked per policy: blocking a candidate frees the queue for downstream candidates.",
            "Outcome PnL is from the FIXED trade-through simulator (Section 8.26 fix).",
        ],
    }
    OUT_SUMMARY.write_text(json.dumps(summary, indent=2, default=str))
    print(f"[recon-v2] wrote {OUT_SUMMARY}")

    # Pretty-print
    print("\n=== No-gate (filterless control) ===")
    for k, v in no_gate_agg.items():
        print(f"  {k:>10s} = {v}")
    print("\n=== With Kalshi gate (corrected semantics) ===")
    for k, v in with_gate_agg.items():
        print(f"  {k:>10s} = {v}")
    print("\n=== Delta (with - no) ===")
    for k, v in delta.items():
        print(f"  {k:>20s} = {v}")
    print(f"\n  VERDICT: {verdict}")

    print("\n=== Per-month (with gate) ===")
    print(with_gate_pm.to_string(index=False))

    return 0


if __name__ == "__main__":
    sys.exit(main())
